<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="de" xml:lang="de"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Jaromir Gerhardt, Luisa Hautzinger, Theresa Knoch, Jako Spretz">

<title>Entwicklung und psychometrische Prüfung der GEB-12 – GEB-12: Entwicklung und psychometrische Prüfung</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-cd40dbeaf3fe06f03e45c8b1ff524ae9.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Keine Treffer",
    "search-matching-documents-text": "Treffer",
    "search-copy-link-title": "Link in die Suche kopieren",
    "search-hide-matches-text": "Zusätzliche Treffer verbergen",
    "search-more-match-text": "weitere Treffer in diesem Dokument",
    "search-more-matches-text": "weitere Treffer in diesem Dokument",
    "search-clear-button-title": "Zurücksetzen",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Abbrechen",
    "search-submit-button-title": "Abschicken",
    "search-label": "Suchen"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="quarto-light">

<div id="quarto-search-results"></div>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Inhaltsverzeichnis</h2>
   
  <ul>
  <li><a href="#einleitung" id="toc-einleitung" class="nav-link active" data-scroll-target="#einleitung"><span class="header-section-number">1</span> Einleitung</a>
  <ul class="collapse">
  <li><a href="#die-langform-geb-50" id="toc-die-langform-geb-50" class="nav-link" data-scroll-target="#die-langform-geb-50"><span class="header-section-number">1.1</span> Die Langform: GEB-50</a></li>
  <li><a href="#motivation-für-eine-kurzform" id="toc-motivation-für-eine-kurzform" class="nav-link" data-scroll-target="#motivation-für-eine-kurzform"><span class="header-section-number">1.2</span> Motivation für eine Kurzform</a></li>
  </ul></li>
  <li><a href="#methoden" id="toc-methoden" class="nav-link" data-scroll-target="#methoden"><span class="header-section-number">2</span> Methoden</a>
  <ul class="collapse">
  <li><a href="#konstruktion-der-kurzform" id="toc-konstruktion-der-kurzform" class="nav-link" data-scroll-target="#konstruktion-der-kurzform"><span class="header-section-number">2.1</span> Konstruktion der Kurzform</a></li>
  <li><a href="#sec-pretest" id="toc-sec-pretest" class="nav-link" data-scroll-target="#sec-pretest"><span class="header-section-number">2.2</span> Pretest: Funktion und statistische Einordnung</a></li>
  <li><a href="#datenerhebung" id="toc-datenerhebung" class="nav-link" data-scroll-target="#datenerhebung"><span class="header-section-number">2.3</span> Datenerhebung</a></li>
  <li><a href="#analyseplan" id="toc-analyseplan" class="nav-link" data-scroll-target="#analyseplan"><span class="header-section-number">2.4</span> Analyseplan</a></li>
  </ul></li>
  <li><a href="#ergebnisse-klassische-testtheorie" id="toc-ergebnisse-klassische-testtheorie" class="nav-link" data-scroll-target="#ergebnisse-klassische-testtheorie"><span class="header-section-number">3</span> Ergebnisse (klassische Testtheorie)</a>
  <ul class="collapse">
  <li><a href="#deskriptive-statistik" id="toc-deskriptive-statistik" class="nav-link" data-scroll-target="#deskriptive-statistik"><span class="header-section-number">3.1</span> Deskriptive Statistik</a></li>
  <li><a href="#reliabilität-alpha-omega-und-split-half" id="toc-reliabilität-alpha-omega-und-split-half" class="nav-link" data-scroll-target="#reliabilität-alpha-omega-und-split-half"><span class="header-section-number">3.2</span> Reliabilität: Alpha, Omega und Split-Half</a></li>
  <li><a href="#korrelation-kurzform-vs.-langform" id="toc-korrelation-kurzform-vs.-langform" class="nav-link" data-scroll-target="#korrelation-kurzform-vs.-langform"><span class="header-section-number">3.3</span> Korrelation Kurzform vs.&nbsp;Langform</a></li>
  </ul></li>
  <li><a href="#ergebnisse-faktorstruktur-und-irt" id="toc-ergebnisse-faktorstruktur-und-irt" class="nav-link" data-scroll-target="#ergebnisse-faktorstruktur-und-irt"><span class="header-section-number">4</span> Ergebnisse (Faktorstruktur und IRT)</a>
  <ul class="collapse">
  <li><a href="#konfirmatorische-faktorenanalyse" id="toc-konfirmatorische-faktorenanalyse" class="nav-link" data-scroll-target="#konfirmatorische-faktorenanalyse"><span class="header-section-number">4.1</span> Konfirmatorische Faktorenanalyse</a></li>
  <li><a href="#rasch-modell-irt" id="toc-rasch-modell-irt" class="nav-link" data-scroll-target="#rasch-modell-irt"><span class="header-section-number">4.2</span> Rasch-Modell (IRT)</a></li>
  </ul></li>
  <li><a href="#diskussion" id="toc-diskussion" class="nav-link" data-scroll-target="#diskussion"><span class="header-section-number">5</span> Diskussion</a>
  <ul class="collapse">
  <li><a href="#ist-die-geb-12-eine-gute-kurzform" id="toc-ist-die-geb-12-eine-gute-kurzform" class="nav-link" data-scroll-target="#ist-die-geb-12-eine-gute-kurzform"><span class="header-section-number">5.1</span> Ist die GEB-12 eine gute Kurzform?</a></li>
  <li><a href="#einschränkungen" id="toc-einschränkungen" class="nav-link" data-scroll-target="#einschränkungen"><span class="header-section-number">5.2</span> Einschränkungen</a></li>
  </ul></li>
  <li><a href="#literatur" id="toc-literatur" class="nav-link" data-scroll-target="#literatur"><span class="header-section-number">6</span> Literatur</a></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Andere Formate</h2><ul><li><a href="index.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">Entwicklung und psychometrische Prüfung der GEB-12</h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Gesamten Code zeigen</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Gesamten Code verbergen</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">Quellcode anzeigen</a></li></ul></div></div>
<p class="subtitle lead">Eine Kurzform der General Ecological Behavior Scale (GEB-50)</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Autor:in</div>
    <div class="quarto-title-meta-contents">
             <p>Jaromir Gerhardt, Luisa Hautzinger, Theresa Knoch, Jako Spretz </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Veröffentlichungsdatum</div>
    <div class="quarto-title-meta-contents">
      <p class="date">30. Juni 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="einleitung" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Einleitung</h1>
<section id="die-langform-geb-50" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="die-langform-geb-50"><span class="header-section-number">1.1</span> Die Langform: GEB-50</h2>
<p>Die <em>General Ecological Behavior Scale</em> (GEB-50) von <span class="citation" data-cites="kaiser2020geb">Kaiser (<a href="#ref-kaiser2020geb" role="doc-biblioref">2020</a>)</span> misst die individuelle Umwelteinstellung über selbstberichtetes ökologisches Verhalten. Theoretische Grundlage ist das <strong>Campbell-Paradigma</strong>: Eine Einstellung zeigt sich in den Verhaltenskosten, die eine Person bereit ist zu tragen, um ein Einstellungsziel zu erreichen. Je kostenintensiver ein Verhalten (z. B. der Verzicht auf ein Auto gegenüber dem Trennen von Altglas), desto stärker die zugrunde liegende Umwelteinstellung.</p>
<p>Die GEB-50 umfasst 50 Items aus <strong>sechs Handlungsbereichen</strong> – Energiesparen, Mobilität, Abfallvermeiden, Konsum, Recycling und gesellschaftliches Engagement. Sie wird über ein <strong>eindimensionales Rasch-Modell</strong> ausgewertet, sodass Personen- und Itemparameter auf einer gemeinsamen latenten Dimension liegen und keine Normierung erforderlich ist <span class="citation" data-cites="kaiser2020geb">(<a href="#ref-kaiser2020geb" role="doc-biblioref">Kaiser, 2020</a>)</span>. Die Vollversion erreicht eine Separationsreliabilität von <span class="math inline">\(rel = .71\)</span> bis <span class="math inline">\(.88\)</span> <span class="citation" data-cites="kaiser2020geb">(<a href="#ref-kaiser2020geb" role="doc-biblioref">Kaiser, 2020</a>)</span>. Belege zur Konstrukt- und Kriteriumsvalidität liegen vor: So korreliert die GEB-50 mit der konstruktnahen NEP-Skala (<em>New Ecological Paradigm</em>) zu <span class="math inline">\(r = .49\)</span>; die prognostische Validität wurde u. a. in einer Untersuchung mit Autofahrer:innen nachgewiesen <span class="citation" data-cites="kaiser2020geb">(<a href="#ref-kaiser2020geb" role="doc-biblioref">Kaiser, 2020</a>)</span>.</p>
</section>
<section id="motivation-für-eine-kurzform" class="level2" data-number="1.2">
<h2 data-number="1.2" class="anchored" data-anchor-id="motivation-für-eine-kurzform"><span class="header-section-number">1.2</span> Motivation für eine Kurzform</h2>
<p>In vielen Anwendungskontexten – Interventionsstudien, wiederholte Messungen, Online-Erhebungen mit knappem Zeitbudget – ist eine 50-Item-Skala unökonomisch. Eine validierte <strong>12-Item-Kurzform (GEB-12)</strong> würde die Erhebungsdauer deutlich senken und gleichzeitig die zentrale Eigenschaft der Langform – die Messung einer einzelnen latenten Umwelteinstellung – erhalten.</p>
<p>Eine Kurzform ist jedoch nicht einfach eine beliebige Item-Teilmenge. <span class="citation" data-cites="smith2000sins">Smith et al. (<a href="#ref-smith2000sins" role="doc-biblioref">2000</a>)</span> warnen ausdrücklich vor „Sünden” der Kurzformentwicklung: Eine Kurzform muss eigenständig auf Reliabilität, faktorielle Struktur und Konstruktvalidität gegenüber der Langform geprüft werden. Genau dieser Prüfung folgt der vorliegende Bericht.</p>
</section>
</section>
<section id="methoden" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Methoden</h1>
<section id="konstruktion-der-kurzform" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="konstruktion-der-kurzform"><span class="header-section-number">2.1</span> Konstruktion der Kurzform</h2>
<p>Die Itemauswahl folgt einem theoriegeleiteten Verfahren in Anlehnung an <span class="citation" data-cites="smith2000sins">Smith et al. (<a href="#ref-smith2000sins" role="doc-biblioref">2000</a>)</span> und die Konstruktionslogik der Langform <span class="citation" data-cites="kaiser2020geb">(<a href="#ref-kaiser2020geb" role="doc-biblioref">Kaiser, 2020</a>)</span>:</p>
<ol type="1">
<li><strong>Inhaltsvalidität:</strong> Alle sechs Handlungsbereiche bleiben vertreten – je <strong>ein leichtes</strong> (geringe Verhaltenskosten) und <strong>ein schweres</strong> Item (hohe Verhaltenskosten) pro Bereich. Das ergibt <span class="math inline">\(6 \times 2 = 12\)</span> Items und sichert die inhaltliche Breite des Konstrukts.</li>
<li><strong>Schwierigkeitsverteilung:</strong> Durch das Paar leicht/schwer wird der gesamte Bereich der Verhaltenskosten abgedeckt; Decken- und Bodeneffekte sollen vermieden werden (Ziel-Schwierigkeiten <span class="math inline">\(P = .20\)</span> bis <span class="math inline">\(.80\)</span>).</li>
<li><strong>Trennschärfe:</strong> Bevorzugt werden Items mit hoher Item-Total-Korrelation (<span class="math inline">\(r_{it} &gt; .40\)</span>).</li>
<li><strong>Rasch-Konformität:</strong> Items sollen die Raschhomogenität der Langform erhalten.</li>
</ol>
<p>Die resultierende Itemauswahl (zwei Items je Bereich) ist in <a href="#tbl-items" class="quarto-xref">Tabelle&nbsp;1</a> dargestellt.</p>
<div class="cell">
<div id="tbl-items" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-items-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabelle&nbsp;1: Itemauswahl der GEB-12 (je Bereich ein leichtes und ein schweres Item)
</figcaption>
<div aria-describedby="tbl-items-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<div class="kable-table">
<table class="cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 10%">
<col style="width: 40%">
<col style="width: 48%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Bereich</th>
<th style="text-align: left;">Leichtes Item (geringe Kosten)</th>
<th style="text-align: left;">Schweres Item (hohe Kosten)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(1) Energiesparen</td>
<td style="text-align: left;">Ich warte, bis ich eine volle Wäschetrommel habe, bevor ich wasche. (Hfg.)</td>
<td style="text-align: left;">Ich beziehe Strom aus erneuerbarer Energie. (Ja/Nein)</td>
</tr>
<tr class="even">
<td style="text-align: left;">(2) Mobilität</td>
<td style="text-align: left;">Für den Arbeits-/Schulweg nutze ich Fahrrad, ÖPNV oder gehe zu Fuß. (Hfg.)</td>
<td style="text-align: left;">Ich verzichte auf ein Auto. (Ja/Nein)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">(3) Abfallvermeiden</td>
<td style="text-align: left;">Wenn ich im Geschäft eine Plastiktüte bekomme, nehme ich sie. (Hfg., neg.)</td>
<td style="text-align: left;">Ich verwende Einkaufstüten oder -taschen mehrfach. (Ja/Nein)</td>
</tr>
<tr class="even">
<td style="text-align: left;">(4) Konsum</td>
<td style="text-align: left;">Ich benutze beim Waschen einen Weichspüler. (Hfg., neg.)</td>
<td style="text-align: left;">Ich kaufe Obst und Gemüse der Jahreszeit entsprechend. (Hfg.)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">(5) Recycling</td>
<td style="text-align: left;">Altglas bringe ich zum Sammelcontainer. (Hfg.)</td>
<td style="text-align: left;">Leere Batterien werfe ich in den Hausmüll. (Ja/Nein, neg.)</td>
</tr>
<tr class="even">
<td style="text-align: left;">(6) Ges. Engagement</td>
<td style="text-align: left;">Ich unterhalte mich mit Bekannten über Umweltverschmutzung &amp; Klimawandel. (Hfg.)</td>
<td style="text-align: left;">Ich boykottiere Produkte von Firmen, die sich nachweislich umweltschädigend verhalten. (Ja/Nein)</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</figure>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Hinweis</span>Antwortformat und Kodierung
</div>
</div>
<div class="callout-body-container callout-body">
<p>Wie in der Langform werden Häufigkeitsantworten (Hfg. ) <strong>dichotomisiert</strong>: <em>oft / sehr oft</em> <span class="math inline">\(\rightarrow 1\)</span>, <em>nie / selten / gelegentlich</em> <span class="math inline">\(\rightarrow 0\)</span> <span class="citation" data-cites="kaiser2020geb">(<a href="#ref-kaiser2020geb" role="doc-biblioref">Kaiser, 2020</a>)</span>. Negativ formulierte Items werden vor der Analyse umgepolt, ja/nein-Items direkt übernommen. Die 12 Items mischen Häufigkeits- und Ja/Nein-Format (gemischtes Modell).</p>
</div>
</div>
</section>
<section id="sec-pretest" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="sec-pretest"><span class="header-section-number">2.2</span> Pretest: Funktion und statistische Einordnung</h2>
<p>Vor der Hauptuntersuchung wurde ein <strong>Pretest mit <span class="math inline">\(N = 6\)</span> Personen</strong> durchgeführt. Seine Funktion war ausschließlich die Prüfung von <strong>Verständlichkeit und Durchführbarkeit</strong> des Fragebogens, nicht die Itemqualität. Bei dieser Fallzahl sind Trennschärfen, Itemschwierigkeiten und Rasch-Parameter zu instabil für verlässliche Entscheidungen; ein Itemaustausch auf dieser Basis hätte die theoriegeleitete, balancierte Auswahl (je Bereich ein leichtes und ein schweres Item) ohne echten Erkenntnisgewinn gefährdet. Da die Items zudem bereits aus der rasch-skalierten, validierten Langform stammen und nach inhaltlichen sowie psychometrischen Kriterien <span class="citation" data-cites="smith2000sins">(<a href="#ref-smith2000sins" role="doc-biblioref">Smith et al., 2000</a>)</span> ausgewählt wurden, war eine empirische Vorab-Filterung an dieser Mini-Stichprobe nicht erforderlich.</p>
<p>Die Pretest-Ergebnisse dienten daher <strong>nur</strong> der Sicherstellung von Verständlichkeit und Durchführbarkeit. Alle berichteten psychometrischen Prüfungen beruhen ausschließlich auf der <strong>Haupterhebung</strong> (<span class="math inline">\(N = 60\)</span>).</p>
</section>
<section id="datenerhebung" class="level2" data-number="2.3">
<h2 data-number="2.3" class="anchored" data-anchor-id="datenerhebung"><span class="header-section-number">2.3</span> Datenerhebung</h2>
<p>Die Datenerhebung erfolgte über die für wissenschaftliche Zwecke frei verfügbare Online-Befragungsplattform <strong>SoSci Survey</strong>. Für die Originalversion (GEB-50) und die entwickelte Kurzform wurden <strong>zwei separate Fragebögen</strong> erstellt, die über einen individuellen Prüfcode miteinander verknüpft werden konnten, sodass die Antworten jeder Person beiden Instrumenten zugeordnet werden können.</p>
<p>Das <strong>GEB-50</strong> umfasst 50 Items aus sechs Verhaltensdimensionen und besteht aus zwei Teilen: einem ersten Teil mit Antworten auf einer <strong>sechsstufigen Likert-Skala</strong> und einem zweiten Teil mit <strong>dichotomen Items</strong> (Antwortformat „Ja”/„Nein”). Die entwickelte <strong>Kurzform (GEB-12)</strong> umfasst zwölf dichotome Items („Ja”/„Nein”); aus jeder der sechs Dimensionen wurden zwei Items ausgewählt.</p>
<p>Die finale Datenerhebung erfolgte im Zeitraum vom <strong>18.06. bis 28.06.2026</strong>. Die Stichprobe setzte sich aus Mitstudierenden sowie Personen aus dem privaten Umfeld der Autor:innen zusammen und stellt somit eine <strong>Gelegenheitsstichprobe</strong> dar. Angestrebt wurde eine Stichprobengröße von mindestens <span class="math inline">\(N = 50\)</span>; nach Ausschluss von Test- und Abbruchfällen umfasst die finale Auswertungsstichprobe <strong><span class="math inline">\(N = 60\)</span></strong> Personen (Kurz- und Langform jeweils 60).</p>
<p>Die Auswahl der zwölf Items für die Kurzform erfolgte <strong>vorrangig auf theoretischer Grundlage</strong>: Pro Handlungsbereich wurden zwei Items bestimmt – ein leichtes und ein schweres –, sodass die sechs Dimensionen vollständig und mit abgestufter Schwierigkeit abgebildet sind (siehe <a href="#sec-pretest" class="quarto-xref">Kapitel&nbsp;2.2</a> sowie die Konstruktionskriterien oben).</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="do">#### load data frames ####</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>Data_S_raw <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"Data_S.csv"</span>, <span class="at">header =</span> <span class="cn">TRUE</span>, <span class="at">sep =</span> <span class="st">";"</span>,</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>                       <span class="at">check.names =</span> <span class="cn">FALSE</span>, <span class="at">fileEncoding =</span> <span class="st">"UCS-2LE"</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>Data_L_raw <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"Data_L.csv"</span>, <span class="at">header =</span> <span class="cn">TRUE</span>, <span class="at">sep =</span> <span class="st">";"</span>,</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>                       <span class="at">check.names =</span> <span class="cn">FALSE</span>, <span class="at">fileEncoding =</span> <span class="st">"UCS-2LE"</span>)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Select cases</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>Data_S_raw <span class="ot">&lt;-</span> Data_S_raw[Data_S_raw<span class="sc">$</span>CASE <span class="sc">!=</span> <span class="dv">28</span> <span class="sc">&amp;</span> Data_S_raw<span class="sc">$</span>CASE <span class="sc">!=</span> <span class="dv">29</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>                     <span class="sc">&amp;</span> Data_S_raw<span class="sc">$</span>CASE <span class="sc">!=</span> <span class="dv">30</span> <span class="sc">&amp;</span> Data_S_raw<span class="sc">$</span>CASE <span class="sc">!=</span> <span class="dv">31</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>                     <span class="sc">&amp;</span> Data_S_raw<span class="sc">$</span>CASE <span class="sc">!=</span> <span class="dv">42</span> <span class="sc">&amp;</span> Data_S_raw<span class="sc">$</span>CASE <span class="sc">!=</span> <span class="dv">94</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>                     <span class="sc">&amp;</span> Data_S_raw<span class="sc">$</span>CASE <span class="sc">!=</span> <span class="dv">111</span>, ]</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>Data_L_raw <span class="ot">&lt;-</span> Data_L_raw[Data_L_raw<span class="sc">$</span>CASE <span class="sc">!=</span> <span class="dv">130</span> <span class="sc">&amp;</span> Data_L_raw<span class="sc">$</span>CASE <span class="sc">!=</span> <span class="dv">153</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>                         <span class="sc">&amp;</span> Data_L_raw<span class="sc">$</span>CASE <span class="sc">!=</span> <span class="dv">155</span> <span class="sc">&amp;</span> Data_L_raw<span class="sc">$</span>CASE <span class="sc">!=</span> <span class="dv">156</span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>                         <span class="sc">&amp;</span> Data_L_raw<span class="sc">$</span>CASE <span class="sc">!=</span> <span class="dv">159</span> <span class="sc">&amp;</span> Data_L_raw<span class="sc">$</span>CASE <span class="sc">!=</span> <span class="dv">164</span></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>                         <span class="sc">&amp;</span> Data_L_raw<span class="sc">$</span>CASE <span class="sc">!=</span> <span class="dv">173</span> <span class="sc">&amp;</span> Data_L_raw<span class="sc">$</span>CASE <span class="sc">!=</span> <span class="dv">175</span></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>                         <span class="sc">&amp;</span> Data_L_raw<span class="sc">$</span>CASE <span class="sc">!=</span> <span class="dv">182</span> <span class="sc">&amp;</span> Data_L_raw<span class="sc">$</span>CASE <span class="sc">!=</span> <span class="dv">196</span></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>                         <span class="sc">&amp;</span> Data_L_raw<span class="sc">$</span>CASE <span class="sc">!=</span> <span class="dv">215</span> <span class="sc">&amp;</span> Data_L_raw<span class="sc">$</span>CASE <span class="sc">!=</span> <span class="dv">224</span></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>                         <span class="sc">&amp;</span> Data_L_raw<span class="sc">$</span>CASE <span class="sc">!=</span> <span class="dv">237</span>, ]</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Short version (GEB-12)</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="co"># select colums</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>Data_S <span class="ot">&lt;-</span> Data_S_raw <span class="sc">%&gt;%</span> <span class="fu">select</span>(KG01_01, KG01_02, KG01_03, KG01_04, KG01_05,</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>                                KG01_06, KG01_07, KG01_08, KG01_09, KG01_10,</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>                                KG01_11, KG01_12)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Recode</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>Data_S <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">sapply</span>(Data_S[<span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">12</span>)], car<span class="sc">::</span>recode, <span class="st">"-1=0; 2=0; 1=1"</span>))</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Recode inverse items</span></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>Data_S[<span class="fu">c</span>(<span class="dv">10</span>)] <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">sapply</span>(Data_S[<span class="fu">c</span>(<span class="dv">10</span>)], car<span class="sc">::</span>recode, <span class="st">"0=1; 1=0"</span>))</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a><span class="do">## Long version (GEB-50)</span></span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>Data_L <span class="ot">&lt;-</span> <span class="fu">unfactor</span>(Data_L_raw[<span class="dv">7</span><span class="sc">:</span><span class="dv">56</span>])</span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Inverse dichotomous items</span></span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a>Data_L[<span class="fu">c</span>(<span class="dv">34</span>,<span class="dv">35</span>,<span class="dv">36</span>,<span class="dv">37</span>,<span class="dv">38</span>,<span class="dv">40</span>)] <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">sapply</span>(Data_L[<span class="fu">c</span>(<span class="dv">34</span>,<span class="dv">35</span>,<span class="dv">36</span>,<span class="dv">37</span>,<span class="dv">38</span>,<span class="dv">40</span>)],</span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a>                                                     car<span class="sc">::</span>recode, <span class="st">"1=2; 2=1"</span>))</span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Recode dichotomous items</span></span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a>Data_L[<span class="fu">c</span>(<span class="dv">33</span><span class="sc">:</span><span class="dv">50</span>)] <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">sapply</span>(Data_L[<span class="fu">c</span>(<span class="dv">33</span><span class="sc">:</span><span class="dv">50</span>)], car<span class="sc">::</span>recode,</span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a>                                         <span class="st">"1=1; 2=0"</span>))</span>
<span id="cb2-23"><a href="#cb2-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-24"><a href="#cb2-24" aria-hidden="true" tabindex="-1"></a><span class="co"># Inverse polytomous items</span></span>
<span id="cb2-25"><a href="#cb2-25" aria-hidden="true" tabindex="-1"></a>Data_L[<span class="fu">c</span>(<span class="dv">3</span>,<span class="dv">4</span>,<span class="dv">6</span>,<span class="dv">7</span>,<span class="dv">10</span>,<span class="dv">17</span>,<span class="dv">18</span>,<span class="dv">23</span>,<span class="dv">26</span>,<span class="dv">27</span>,<span class="dv">28</span>,<span class="dv">29</span>,<span class="dv">31</span>)] <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(</span>
<span id="cb2-26"><a href="#cb2-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sapply</span>(Data_L[<span class="fu">c</span>(<span class="dv">3</span>,<span class="dv">4</span>,<span class="dv">6</span>,<span class="dv">7</span>,<span class="dv">10</span>,<span class="dv">17</span>,<span class="dv">18</span>,<span class="dv">23</span>,<span class="dv">26</span>,<span class="dv">27</span>,<span class="dv">28</span>,<span class="dv">29</span>,<span class="dv">31</span>)],</span>
<span id="cb2-27"><a href="#cb2-27" aria-hidden="true" tabindex="-1"></a>         car<span class="sc">::</span>recode,  <span class="st">"1=5; 2=4; 3=3; 4=2; 5=1"</span>))</span>
<span id="cb2-28"><a href="#cb2-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-29"><a href="#cb2-29" aria-hidden="true" tabindex="-1"></a><span class="co"># Dichotomize polytomous items</span></span>
<span id="cb2-30"><a href="#cb2-30" aria-hidden="true" tabindex="-1"></a>Data_L[<span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">32</span>)] <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">sapply</span>(Data_L[<span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">32</span>)], car<span class="sc">::</span>recode,</span>
<span id="cb2-31"><a href="#cb2-31" aria-hidden="true" tabindex="-1"></a>                                        <span class="st">"1=0; 2=0; 3=0; 4=1; 5=1"</span>))</span>
<span id="cb2-32"><a href="#cb2-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-33"><a href="#cb2-33" aria-hidden="true" tabindex="-1"></a><span class="co"># Data type -&gt; numeric</span></span>
<span id="cb2-34"><a href="#cb2-34" aria-hidden="true" tabindex="-1"></a>i <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">50</span>)</span>
<span id="cb2-35"><a href="#cb2-35" aria-hidden="true" tabindex="-1"></a>Data_L[, i] <span class="ot">&lt;-</span> <span class="fu">apply</span>(Data_L[, i], <span class="dv">2</span>, <span class="cf">function</span>(x) <span class="fu">as.numeric</span>(<span class="fu">as.character</span>(x)))</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</section>
<section id="analyseplan" class="level2" data-number="2.4">
<h2 data-number="2.4" class="anchored" data-anchor-id="analyseplan"><span class="header-section-number">2.4</span> Analyseplan</h2>
<p>Der Bericht prüft die Kurzform parallel zur Langform mit Verfahren der klassischen Testtheorie (KTT) und der Item-Response-Theorie (IRT). Im Einzelnen: deskriptive Statistik (Mittelwert, SD, Median der Personenscores), drei Reliabilitätsschätzer – <strong>Cronbachs <span class="math inline">\(\alpha\)</span></strong>, <strong>McDonalds <span class="math inline">\(\omega\)</span></strong> (über die sechs Handlungsbereiche) und <strong>Split-Half-Reliabilität</strong> –, die <strong>Spearman- Korrelation</strong> der Summenscores von Kurz- und Langform, eine <strong>konfirmatorische Faktorenanalyse</strong> des Sechs-Bereiche-Modells (WLSMV-Schätzer für dichotome Items) sowie ein <strong>dichotomes Rasch-Modell</strong> (<code>eRm</code>) mit Personenparametern und Separationsreliabilität. Als Zielkriterien gelten <span class="math inline">\(\alpha / \omega \geq .70\)</span>, eine hohe Korrelation der Summenscores <span class="citation" data-cites="smith2000sins">(<a href="#ref-smith2000sins" role="doc-biblioref">Smith et al., 2000</a>)</span> sowie akzeptable CFA-Fitwerte (CFI <span class="math inline">\(&gt; .95\)</span>, RMSEA <span class="math inline">\(&lt; .06\)</span>, SRMR <span class="math inline">\(&lt; .08\)</span>). Fit-Indizes sind dabei nur aussagekräftig, wenn das Modell stabil identifiziert ist; bei Schätzproblemen (Nicht-Konvergenz, unzulässige Parameter) werden sie nicht inhaltlich interpretiert.</p>
</section>
</section>
<section id="ergebnisse-klassische-testtheorie" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Ergebnisse (klassische Testtheorie)</h1>
<section id="deskriptive-statistik" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="deskriptive-statistik"><span class="header-section-number">3.1</span> Deskriptive Statistik</h2>
<p>Zunächst werden Item- und Skalenkennwerte für Kurz- und Langform beschrieben. <a href="#tbl-deskriptiv" class="quarto-xref">Tabelle&nbsp;2</a> zeigt für jedes GEB-12-Item die Schwierigkeit <span class="math inline">\(P\)</span> (Anteil zustimmender Antworten) und die part-whole-korrigierte Trennschärfe <span class="math inline">\(r_{it}\)</span>, ergänzt um eine Enschätzung.</p>
<div class="cell">
<div id="tbl-deskriptiv" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-deskriptiv-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabelle&nbsp;2: Itemkennwerte der GEB-12 (Schwierigkeit, Trennschärfe)
</figcaption>
<div aria-describedby="tbl-deskriptiv-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<div class="kable-table">
<table class="cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 12%">
<col style="width: 22%">
<col style="width: 18%">
<col style="width: 25%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Item</th>
<th style="text-align: right;">Schwierigkeit_P</th>
<th style="text-align: left;">Bewertung_P</th>
<th style="text-align: right;">Trennschaerfe_rit</th>
<th style="text-align: left;">Bewertung_rit</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">KG01_01</td>
<td style="text-align: right;">0.80</td>
<td style="text-align: left;">ok</td>
<td style="text-align: right;">0.16</td>
<td style="text-align: left;">kritisch</td>
</tr>
<tr class="even">
<td style="text-align: left;">KG01_02</td>
<td style="text-align: right;">0.53</td>
<td style="text-align: left;">ok</td>
<td style="text-align: right;">0.19</td>
<td style="text-align: left;">kritisch</td>
</tr>
<tr class="odd">
<td style="text-align: left;">KG01_03</td>
<td style="text-align: right;">0.85</td>
<td style="text-align: left;">Decken/Boden</td>
<td style="text-align: right;">0.12</td>
<td style="text-align: left;">kritisch</td>
</tr>
<tr class="even">
<td style="text-align: left;">KG01_04</td>
<td style="text-align: right;">0.57</td>
<td style="text-align: left;">ok</td>
<td style="text-align: right;">0.19</td>
<td style="text-align: left;">kritisch</td>
</tr>
<tr class="odd">
<td style="text-align: left;">KG01_05</td>
<td style="text-align: right;">0.83</td>
<td style="text-align: left;">Decken/Boden</td>
<td style="text-align: right;">0.12</td>
<td style="text-align: left;">kritisch</td>
</tr>
<tr class="even">
<td style="text-align: left;">KG01_06</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: left;">Decken/Boden</td>
<td style="text-align: right;">0.14</td>
<td style="text-align: left;">kritisch</td>
</tr>
<tr class="odd">
<td style="text-align: left;">KG01_07</td>
<td style="text-align: right;">0.63</td>
<td style="text-align: left;">ok</td>
<td style="text-align: right;">0.30</td>
<td style="text-align: left;">grenzwertig</td>
</tr>
<tr class="even">
<td style="text-align: left;">KG01_08</td>
<td style="text-align: right;">0.52</td>
<td style="text-align: left;">ok</td>
<td style="text-align: right;">0.33</td>
<td style="text-align: left;">grenzwertig</td>
</tr>
<tr class="odd">
<td style="text-align: left;">KG01_09</td>
<td style="text-align: right;">0.93</td>
<td style="text-align: left;">Decken/Boden</td>
<td style="text-align: right;">0.04</td>
<td style="text-align: left;">kritisch</td>
</tr>
<tr class="even">
<td style="text-align: left;">KG01_10-</td>
<td style="text-align: right;">0.10</td>
<td style="text-align: left;">Decken/Boden</td>
<td style="text-align: right;">0.04</td>
<td style="text-align: left;">kritisch</td>
</tr>
<tr class="odd">
<td style="text-align: left;">KG01_11</td>
<td style="text-align: right;">0.83</td>
<td style="text-align: left;">Decken/Boden</td>
<td style="text-align: right;">0.25</td>
<td style="text-align: left;">kritisch</td>
</tr>
<tr class="even">
<td style="text-align: left;">KG01_12</td>
<td style="text-align: right;">0.15</td>
<td style="text-align: left;">Decken/Boden</td>
<td style="text-align: right;">0.36</td>
<td style="text-align: left;">grenzwertig</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</figure>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Personen-Mittelwerte (Mittelwert, SD, Median) je Skala</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>Data_S_Mean <span class="ot">&lt;-</span> <span class="fu">rowMeans</span>(Data_S, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>Data_L_Mean <span class="ot">&lt;-</span> <span class="fu">rowMeans</span>(Data_L, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>psych<span class="sc">::</span><span class="fu">describe</span>(Data_S_Mean)   <span class="co"># GEB-12</span></span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div class="kable-table">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 2%">
<col style="width: 4%">
<col style="width: 2%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 6%">
<col style="width: 9%">
<col style="width: 7%">
<col style="width: 9%">
<col style="width: 3%">
<col style="width: 9%">
<col style="width: 10%">
<col style="width: 8%">
<col style="width: 9%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">vars</th>
<th style="text-align: right;">n</th>
<th style="text-align: right;">mean</th>
<th style="text-align: right;">sd</th>
<th style="text-align: right;">median</th>
<th style="text-align: right;">trimmed</th>
<th style="text-align: right;">mad</th>
<th style="text-align: right;">min</th>
<th style="text-align: right;">max</th>
<th style="text-align: right;">range</th>
<th style="text-align: right;">skew</th>
<th style="text-align: right;">kurtosis</th>
<th style="text-align: right;">se</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">X1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">60</td>
<td style="text-align: right;">0.7083333</td>
<td style="text-align: right;">0.1538122</td>
<td style="text-align: right;">0.75</td>
<td style="text-align: right;">0.7135417</td>
<td style="text-align: right;">0.12355</td>
<td style="text-align: right;">0.1666667</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.8333333</td>
<td style="text-align: right;">-0.5327565</td>
<td style="text-align: right;">1.050655</td>
<td style="text-align: right;">0.0198571</td>
</tr>
</tbody>
</table>
</div>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>psych<span class="sc">::</span><span class="fu">describe</span>(Data_L_Mean)   <span class="co"># GEB-50</span></span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div class="kable-table">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 2%">
<col style="width: 4%">
<col style="width: 2%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 6%">
<col style="width: 9%">
<col style="width: 8%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 5%">
<col style="width: 10%">
<col style="width: 8%">
<col style="width: 9%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">vars</th>
<th style="text-align: right;">n</th>
<th style="text-align: right;">mean</th>
<th style="text-align: right;">sd</th>
<th style="text-align: right;">median</th>
<th style="text-align: right;">trimmed</th>
<th style="text-align: right;">mad</th>
<th style="text-align: right;">min</th>
<th style="text-align: right;">max</th>
<th style="text-align: right;">range</th>
<th style="text-align: right;">skew</th>
<th style="text-align: right;">kurtosis</th>
<th style="text-align: right;">se</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">X1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">60</td>
<td style="text-align: right;">0.5893333</td>
<td style="text-align: right;">0.1509054</td>
<td style="text-align: right;">0.62</td>
<td style="text-align: right;">0.6008333</td>
<td style="text-align: right;">0.118608</td>
<td style="text-align: right;">0.06</td>
<td style="text-align: right;">0.86</td>
<td style="text-align: right;">0.8</td>
<td style="text-align: right;">-0.9172406</td>
<td style="text-align: right;">1.205699</td>
<td style="text-align: right;">0.0194818</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</section>
<section id="reliabilität-alpha-omega-und-split-half" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="reliabilität-alpha-omega-und-split-half"><span class="header-section-number">3.2</span> Reliabilität: Alpha, Omega und Split-Half</h2>
<p>Berichtet werden drei Reliabilitätsschätzer, jeweils für Kurz- und Langform.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="do">#### Cronbachs Alpha ####</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>psych<span class="sc">::</span><span class="fu">alpha</span>(Data_S, <span class="at">check.keys =</span> <span class="cn">TRUE</span>)   <span class="co"># GEB-12</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>psych<span class="sc">::</span><span class="fu">alpha</span>(Data_L, <span class="at">check.keys =</span> <span class="cn">TRUE</span>)   <span class="co"># GEB-50</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="do">#### McDonalds Omega ueber die sechs Handlungsbereiche ####</span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>psych<span class="sc">::</span><span class="fu">omega</span>(Data_S, <span class="at">nfactors =</span> <span class="dv">6</span>, <span class="at">plot =</span> <span class="cn">FALSE</span>)        <span class="co"># GEB-12</span></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>psych<span class="sc">::</span><span class="fu">omega</span>(Data_L, <span class="at">nfactors =</span> <span class="dv">6</span>, <span class="at">plot =</span> <span class="cn">FALSE</span>)        <span class="co"># GEB-50</span></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a><span class="do">#### Split-Half-Reliabilitaet ####</span></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a><span class="fu">splitHalf</span>(Data_S)                         <span class="co"># GEB-12</span></span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a><span class="fu">splitHalf</span>(Data_L)                         <span class="co"># GEB-50</span></span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div class="cell">
<div class="cell-output-display">
<div class="kable-table">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Skala</th>
<th style="text-align: right;">Cronbachs_Alpha</th>
<th style="text-align: right;">Omega_total</th>
<th style="text-align: right;">Split_Half_mean</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">GEB-12 (Kurzform)</td>
<td style="text-align: right;">0.50</td>
<td style="text-align: right;">0.72</td>
<td style="text-align: right;">0.47</td>
</tr>
<tr class="even">
<td style="text-align: left;">GEB-50 (Langform)</td>
<td style="text-align: right;">0.87</td>
<td style="text-align: right;">0.92</td>
<td style="text-align: right;">0.88</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tipp</span>Maßstab und Befund
</div>
</div>
<div class="callout-body-container callout-body">
<p>Als Zielwert gilt <span class="math inline">\(\alpha \geq .70\)</span>. Eine <strong>Reduktion</strong> gegenüber der Separationsreliabilität der Vollversion (<span class="math inline">\(.71\)</span>–<span class="math inline">\(.88\)</span>) wäre angesichts der starken Kürzung erwartbar und solange unkritisch, wie <span class="math inline">\(.70\)</span> erreicht wird. Tatsächlich verfehlt die GEB-12 dieses Kriterium mit <span class="math inline">\(\alpha = .50\)</span> (Split-Half <span class="math inline">\(.47\)</span>) jedoch deutlich, während die Langform mit <span class="math inline">\(\alpha = .87\)</span> klar darüber liegt. Der Wert Omega total <span class="math inline">\(= .72\)</span> ist wegen Überparametrisierung (sechs Faktoren, zwölf Items) nicht belastbar.</p>
</div>
</div>
</section>
<section id="korrelation-kurzform-vs.-langform" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="korrelation-kurzform-vs.-langform"><span class="header-section-number">3.3</span> Korrelation Kurzform vs.&nbsp;Langform</h2>
<p>Das Kernkriterium der Konstruktvalidität nach <span class="citation" data-cites="smith2000sins">Smith et al. (<a href="#ref-smith2000sins" role="doc-biblioref">2000</a>)</span> ist die Übereinstimmung der Personenwerte beider Formen.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="do">### Bravais pearson correlation ####</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>Sum_L <span class="ot">&lt;-</span> <span class="fu">rowSums</span>(Data_L, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)   <span class="co"># GEB-50</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>Sum_S <span class="ot">&lt;-</span> <span class="fu">rowSums</span>(Data_S, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)   <span class="co"># GEB-12</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Spearman-Rangkorrelation</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(Sum_L, Sum_S, <span class="at">method =</span> <span class="st">"spearman"</span>)</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2951678</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div class="kable-table">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Kennwert</th>
<th style="text-align: right;">Wert</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">N</td>
<td style="text-align: right;">60.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Spearman-Rho (GEB-50 x GEB-12)</td>
<td style="text-align: right;">0.3</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Mittelwert Summenscore GEB-50</td>
<td style="text-align: right;">29.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mittelwert Summenscore GEB-12</td>
<td style="text-align: right;">8.5</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>Eine hohe Korrelation würde belegen, dass die Kurzform die Personenordnung der Langform weitgehend reproduziert. Mit <span class="math inline">\(\rho = .30\)</span> besteht jedoch nur ein mittlerer Zusammenhang, der deutlich unter dem für eine valide Kurzform erwartbaren Niveau liegt. Dabei ist zu beachten, dass dieser Wert die Übereinstimmung sogar noch <strong>überschätzt</strong>: Die zwölf Items sind in der Langform enthalten (Item-Overlap), und die niedrige Reliabilität der Kurzform (<span class="math inline">\(\alpha = .50\)</span>) deckelt die maximal erreichbare Korrelation rechnerisch nach oben – ein klassischer Effekt im Sinne von <span class="citation" data-cites="smith2000sins">Smith et al. (<a href="#ref-smith2000sins" role="doc-biblioref">2000</a>)</span>.</p>
</section>
</section>
<section id="ergebnisse-faktorstruktur-und-irt" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Ergebnisse (Faktorstruktur und IRT)</h1>
<section id="konfirmatorische-faktorenanalyse" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="konfirmatorische-faktorenanalyse"><span class="header-section-number">4.1</span> Konfirmatorische Faktorenanalyse</h2>
<p>Geprüft wird die faktorielle Struktur der GEB-12 über ein <strong>Sechs-Faktoren- Modell</strong>, das die sechs Handlungsbereiche als latente Faktoren mit je zwei Indikatoren abbildet. Da die Items dichotom sind, wird der Schätzer <code>WLSMV</code> mit Deklaration der Items als <code>ordered</code> verwendet.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="do">#### CFA_Model ####</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Sechs-Faktoren-Modell (je Handlungsbereich ein Faktor mit 2 Items)</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>CFA_model <span class="ot">&lt;-</span> <span class="st">'</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="st">Energiesparen =~ KG01_01 + KG01_02</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a><span class="st">Mobilität =~ KG01_03 + KG01_04</span></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a><span class="st">Abfallvermeiden =~ KG01_05 + KG01_06</span></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a><span class="st">Konsum =~ KG01_07 + KG01_08</span></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a><span class="st">Recycling =~ KG01_09 + KG01_10</span></span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a><span class="st">Engagement =~ KG01_11 + KG01_12</span></span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a><span class="st">'</span></span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>lavaan<span class="sc">::</span><span class="fu">cfa</span>(CFA_model, <span class="at">data =</span> Data_S)</span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>Items_S <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"KG01_01"</span>, <span class="st">"KG01_02"</span>,</span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a>  <span class="st">"KG01_03"</span>, <span class="st">"KG01_04"</span>,</span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a>  <span class="st">"KG01_05"</span>, <span class="st">"KG01_06"</span>,</span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a>  <span class="st">"KG01_07"</span>, <span class="st">"KG01_08"</span>,</span>
<span id="cb8-18"><a href="#cb8-18" aria-hidden="true" tabindex="-1"></a>  <span class="st">"KG01_09"</span>, <span class="st">"KG01_10"</span>,</span>
<span id="cb8-19"><a href="#cb8-19" aria-hidden="true" tabindex="-1"></a>  <span class="st">"KG01_11"</span>, <span class="st">"KG01_12"</span>)</span>
<span id="cb8-20"><a href="#cb8-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-21"><a href="#cb8-21" aria-hidden="true" tabindex="-1"></a>Fit <span class="ot">&lt;-</span> <span class="fu">cfa</span>(CFA_model, <span class="at">data =</span> Data_S,</span>
<span id="cb8-22"><a href="#cb8-22" aria-hidden="true" tabindex="-1"></a>                   <span class="at">ordered =</span> Items_S, <span class="at">estimator =</span> <span class="st">"WLSMV"</span>)</span>
<span id="cb8-23"><a href="#cb8-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-24"><a href="#cb8-24" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(Fit, <span class="at">fit.measures =</span> <span class="cn">TRUE</span>, <span class="at">standardized =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code> chisq.scaled            df pvalue.scaled    cfi.scaled    tli.scaled 
       28.933        39.000         0.881         1.000         1.473 
 rmsea.scaled          srmr 
        0.000         0.134 </code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div class="kable-table">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">lhs</th>
<th style="text-align: left;">rhs</th>
<th style="text-align: right;">est.std</th>
<th style="text-align: right;">pvalue</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Energiesparen</td>
<td style="text-align: left;">KG01_01</td>
<td style="text-align: right;">0.6105044</td>
<td style="text-align: right;">0.0156373</td>
</tr>
<tr class="even">
<td style="text-align: left;">Energiesparen</td>
<td style="text-align: left;">KG01_02</td>
<td style="text-align: right;">0.8093655</td>
<td style="text-align: right;">0.0003434</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Mobilität</td>
<td style="text-align: left;">KG01_03</td>
<td style="text-align: right;">0.5212934</td>
<td style="text-align: right;">0.0225188</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mobilität</td>
<td style="text-align: left;">KG01_04</td>
<td style="text-align: right;">1.5355235</td>
<td style="text-align: right;">0.0122640</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Abfallvermeiden</td>
<td style="text-align: left;">KG01_05</td>
<td style="text-align: right;">0.1548293</td>
<td style="text-align: right;">0.7857205</td>
</tr>
<tr class="even">
<td style="text-align: left;">Abfallvermeiden</td>
<td style="text-align: left;">KG01_06</td>
<td style="text-align: right;">4.1253159</td>
<td style="text-align: right;">0.7756867</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Konsum</td>
<td style="text-align: left;">KG01_07</td>
<td style="text-align: right;">0.7111080</td>
<td style="text-align: right;">0.0000045</td>
</tr>
<tr class="even">
<td style="text-align: left;">Konsum</td>
<td style="text-align: left;">KG01_08</td>
<td style="text-align: right;">0.6564094</td>
<td style="text-align: right;">0.0002348</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Recycling</td>
<td style="text-align: left;">KG01_09</td>
<td style="text-align: right;">0.9663071</td>
<td style="text-align: right;">0.0328221</td>
</tr>
<tr class="even">
<td style="text-align: left;">Recycling</td>
<td style="text-align: left;">KG01_10</td>
<td style="text-align: right;">0.3411146</td>
<td style="text-align: right;">0.2285152</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Engagement</td>
<td style="text-align: left;">KG01_11</td>
<td style="text-align: right;">0.4488838</td>
<td style="text-align: right;">0.0356310</td>
</tr>
<tr class="even">
<td style="text-align: left;">Engagement</td>
<td style="text-align: left;">KG01_12</td>
<td style="text-align: right;">0.7794233</td>
<td style="text-align: right;">0.0160495</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Hinweis</span>Stichproben- und Identifikationsvorbehalt
</div>
</div>
<div class="callout-body-container callout-body">
<p>Das Sechs-Faktoren-Modell hat Faktoren mit je nur <strong>zwei Indikatoren</strong>; solche Faktoren sind einzeln nicht identifiziert und nur über die Faktorkovarianzen schätzbar. In Kombination mit <span class="math inline">\(N = 60\)</span> und 12 dichotomen Items ist die CFA <strong>schwach gepowert</strong>: Schätzungen können Warnungen erzeugen, und die Fit-Indizes (CFI <span class="math inline">\(&gt; .95\)</span>, RMSEA <span class="math inline">\(&lt; .06\)</span> als Zielwerte) sind mit Vorsicht zu interpretieren. Sie werden daher gemeinsam mit den Reliabilitäts- und Rasch-Ergebnissen bewertet.</p>
</div>
</div>
</section>
<section id="rasch-modell-irt" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="rasch-modell-irt"><span class="header-section-number">4.2</span> Rasch-Modell (IRT)</h2>
<p>Da die Langform rasch-skaliert ist, wird geprüft, ob die 12 Items das <strong>dichotome Rasch-Modell</strong> erfüllen →<span class="citation" data-cites="rasch1960">(<a href="#ref-rasch1960" role="doc-biblioref">Rasch, 1960</a>)</span>. Geschätzt wird mit dem Paket <code>eRm</code> (konditionale Maximum-Likelihood).</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="do">#### Rasch model ####</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Rasch-Modell schätzen</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>Rasch <span class="ot">&lt;-</span> <span class="fu">RM</span>(Data_S)</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a><span class="fu">RM</span>(Data_S)                               </span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Itemparameter (Lokationen)</span></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a><span class="do">#### Person parameters ####</span></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>Person <span class="ot">&lt;-</span> <span class="fu">person.parameter</span>(Rasch)</span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>Person                                 </span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Personenparameter (theta)</span></span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a><span class="do">#### Separation reliability ####</span></span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a><span class="fu">SepRel</span>(Person)</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div class="cell">
<div class="cell-output-display">
<div class="kable-table">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Kennwert</th>
<th style="text-align: right;">Wert</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">N (effektiv, ohne Extremscores)</td>
<td style="text-align: right;">60.00</td>
</tr>
<tr class="even">
<td style="text-align: left;">Anzahl Items</td>
<td style="text-align: right;">12.00</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Itemschwierigkeit Beta min</td>
<td style="text-align: right;">-1.98</td>
</tr>
<tr class="even">
<td style="text-align: left;">Itemschwierigkeit Beta max</td>
<td style="text-align: right;">3.20</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Separationsreliabilität</td>
<td style="text-align: right;">0.42</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Hinweis</span>Befund und Stichprobe
</div>
</div>
<div class="callout-body-container callout-body">
<p>Die Separationsreliabilität beträgt nur <span class="math inline">\(.42\)</span>: Das Modell trennt die Personen also schwach, was das Bild der niedrigen internen Konsistenz bestätigt. Die Itemschwierigkeiten streuen zwar breit (von <span class="math inline">\(\beta = -1.98\)</span> bis <span class="math inline">\(\beta = 3.20\)</span>), die geringe Separation bleibt davon jedoch unberührt. Generell sind bei <span class="math inline">\(N = 60\)</span> und 12 Items die CML-Schätzungen mit breiten Konfidenzintervallen behaftet.</p>
</div>
</div>
</section>
</section>
<section id="diskussion" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Diskussion</h1>
<section id="ist-die-geb-12-eine-gute-kurzform" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="ist-die-geb-12-eine-gute-kurzform"><span class="header-section-number">5.1</span> Ist die GEB-12 eine gute Kurzform?</h2>
<p>Die Bewertung folgt den Zielkriterien aus dem Analyseplan. Im Ergebnis <strong>verfehlt die GEB-12 die psychometrischen Zielkriterien deutlich</strong>, während die Langform GEB-50 ihre Gütekriterien klar erfüllt. Die einzelnen Befunde:</p>
<ul>
<li><strong>Interne Konsistenz:</strong> Die Langform erreicht ein Cronbachs <span class="math inline">\(\alpha = .87\)</span> (Split-Half <span class="math inline">\(.88\)</span>, Omega total <span class="math inline">\(.92\)</span>) und misst die Umwelteinstellung intern konsistent. Die Kurzform bleibt mit <span class="math inline">\(\alpha = .50\)</span> und einer durchschnittlichen Split-Half-Reliabilität von <span class="math inline">\(.47\)</span> klar unter dem Zielwert <span class="math inline">\(.70\)</span>. Der zunächst akzeptabel wirkende Wert von Omega total <span class="math inline">\(= .72\)</span> ist nicht belastbar: Bei zwölf Items auf sechs Faktoren ist das Omega-Modell überparametrisiert (Omega hierarchical nur <span class="math inline">\(.34\)</span>), sodass dieser Wert die tatsächliche Reliabilität überschätzt.</li>
<li><strong>Korrelation Kurz-/Langform:</strong> Die Summenscores korrelieren nur zu <span class="math inline">\(\rho = .30\)</span> (Spearman) - ein lediglich mittlerer Zusammenhang. Für eine valide Kurzform wäre ein deutlich höherer Wert zu erwarten <span class="citation" data-cites="smith2000sins">(<a href="#ref-smith2000sins" role="doc-biblioref">Smith et al., 2000</a>)</span>. Die GEB-12 reproduziert die Personenordnung der Langform also nur eingeschränkt.</li>
<li><strong>Faktorstruktur:</strong> Die scheinbar perfekten Fit-Indizes (CFI <span class="math inline">\(= 1.00\)</span>, RMSEA <span class="math inline">\(= .00\)</span>) sind vermutlich <strong>Artefakte eines nicht stabil identifizierten Modells</strong>: Bereits der erste, ungerichtete CFA-Aufruf konvergierte nicht, und die WLSMV-Lösung weist unzulässige Schätzwerte auf (eine standardisierte Faktorladung <span class="math inline">\(&gt; 1\)</span> bei KG01_06 sowie negative Residualvarianzen). Der einzige hier belastbare Fit-Index ist der SRMR <span class="math inline">\(= .13\)</span> welcher über dem Grenzwert von <span class="math inline">\(.08\)</span> liegt. Die CFA bestätigt die Sechs-Faktoren-Struktur somit <strong>nicht</strong>.</li>
<li><strong>Rasch-Modell:</strong> Die Separationsreliabilität beträgt <span class="math inline">\(.42\)</span>; das Modell trennt die Personen also unzureichend. Die Itemschwierigkeiten streuen breit (von <span class="math inline">\(\beta = -1.98\)</span> für KG01_06 bis <span class="math inline">\(\beta = 3.20\)</span> für KG01_12). Dies spiegelt die beabsichtigte Mischung leichter und schwerer Items, jedoch bestätigt die geringe Separation das Bild der niedrigen internen Konsistenz.</li>
</ul>
<p>Eine Ursache zeigt sich in der Itemanalyse (siehe <a href="#tbl-deskriptiv" class="quarto-xref">Tabelle&nbsp;2</a>): Die meisten GEB-12-Items haben <strong>Trennschärfen unter <span class="math inline">\(.30\)</span></strong> (kritisch); nur KG01_07, KG01_08 und KG01_12 erreichen grenzwertige Werte um <span class="math inline">\(.30\)</span>–<span class="math inline">\(.36\)</span>. Zudem liegen mehrere Items im Decken- bzw. Bodenbereich (z. B. KG01_06 mit <span class="math inline">\(P = .95\)</span>, KG01_12 mit <span class="math inline">\(P = .15\)</span>). Niedrige Trennschärfen senken unmittelbar die Reliabilität. Dies erklärt das niedrige <span class="math inline">\(\alpha\)</span> und die schwache Rasch-Trennung.</p>
<p>In ihrer jetzigen Form ist die GEB-12 <strong>keine ausreichend reliable und valide Kurzform</strong> der GEB-50. Dieser Befund ist jedoch gut erklärbar und methodisch lehrreich: Die hohe Güte der Langform (<span class="math inline">\(\alpha = .87\)</span>) zeigt, dass das Ausgangsinstrument solide ist. Das Problem liegt also nicht im generellen Konstrukt, sondern in der <strong>Kürzung</strong>. Eine bewusst über sechs heterogene Handlungsbereiche gestreute Auswahl von nur zwei Items pro Bereich maximiert zwar die inhaltliche Breite, minimiert aber zwangsläufig die Inter-Item-Korrelationen (durchschnittlich nur <span class="math inline">\(.07\)</span>) sowie die interne Konsistenz. Genau dies ist eine der von <span class="citation" data-cites="smith2000sins">Smith et al. (<a href="#ref-smith2000sins" role="doc-biblioref">2000</a>)</span> beschriebenen Spannungen der Kurzformentwicklung: Breite und interne Konsistenz lassen sich bei extremer Kürzung nicht gleichzeitig maximieren.</p>
<p>Für eine Weiterentwicklung ergeben sich hier konkrete Ansatzpunkte: Items mit sehr niedriger Trennschärfe oder extremer Schwierigkeit (etwa KG01_06 und KG01_09) könnten gegen trennschärfere Items desselben Bereichs ausgetauscht, die Itemzahl pro Bereich moderat erhöht oder es könnte auf eine einzelne Reliabilitätskennzahl als Hauptkriterium verzichtet werden, zugunsten einer explizit mehrdimensionalen Konzeption. Eine größere und heterogenere Stichprobe würde zudem stabilere CFA- und Rasch-Schätzungen ermöglichen.</p>
</section>
<section id="einschränkungen" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="einschränkungen"><span class="header-section-number">5.2</span> Einschränkungen</h2>
<p>Die wichtigste Einschränkung ist der <strong>Stichprobenumfang</strong> (<span class="math inline">\(N = 60\)</span>). Er erlaubt orientierende KTT-Kennwerte, ist für CFA und IRT mit 12 dichotomen Items aber klein. Die Fit- und Itemparameter sind entsprechend unsicher. Aus demselben Grund konnte der vorgeschaltete Pretest mit <span class="math inline">\(N = 6\)</span> nur die Verständlichkeit und Durchführbarkeit absichern und keine belastbare Itemselektion leisten (siehe <a href="#sec-pretest" class="quarto-xref">Kapitel&nbsp;2.2</a>).</p>
<p>Eine weitere Einschränkung betrifft den <strong>Umgang mit fehlenden Werten</strong>: Zur Vereinfachung der Auswertung wurde die explizite <em>Keine-Angabe</em>-Option (NA) nicht gesondert modelliert, sondern im Recoding mit „trifft nicht zu” (0) zusammengefasst. Dies kann die Antwortverteilung verzerren, da eine bewusste Enthaltung nicht dasselbe ist wie eine Verneinung des Verhaltens. Diese Vereinfachung wurde im Vorfeld nicht ausreichend bedacht und sollte in einer Folgeerhebung sauber getrennt behandelt werden.</p>
<p>Schließlich handelt es sich um eine <strong>Gelegenheitsstichprobe</strong>, die sich überwiegend aus Studierenden sowie Personen aus dem privaten Umfeld der Autor:innen zusammensetzt. Sie ist damit nicht repräsentativ für die Allgemeinbevölkerung; die Ergebnisse sind als <strong>Machbarkeitsnachweis</strong> der theoriegeleiteten Kurzform zu verstehen, nicht als abschließende Validierung.</p>
</section>
</section>
<section id="literatur" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Literatur</h1>
<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list">
<div id="ref-kaiser2020geb" class="csl-entry" role="listitem">
Kaiser, F. G. (2020). <em><span>GEB-50. General Ecological Behavior Scale</span> [Verfahrensdokumentation]</em>. In ZPID (Hrsg.), Open Test Archive. Trier: ZPID. <a href="https://doi.org/10.23668/psycharchives.4489">https://doi.org/10.23668/psycharchives.4489</a>
</div>
<div id="ref-rasch1960" class="csl-entry" role="listitem">
Rasch, G. (1960). <em>Probabilistic Models for Some Intelligence and Attainment Tests</em>. Danmarks Paedagogiske Institut.
</div>
<div id="ref-smith2000sins" class="csl-entry" role="listitem">
Smith, G. T., McCarthy, D. M., &amp; Anderson, K. G. (2000). On the sins of short-form development. <em>Psychological Assessment</em>, <em>12</em>(1), 102–111. <a href="https://doi.org/10.1037/1040-3590.12.1.102">https://doi.org/10.1037/1040-3590.12.1.102</a>
</div>
</div>


<!-- -->

</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Kopiert");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Kopiert");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/neinromir-lab\.github\.io\/Projekt-GEB12\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Quellcode</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb11" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Entwicklung und psychometrische Prüfung der GEB-12"</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="an">subtitle:</span><span class="co"> "Eine Kurzform der General Ecological Behavior Scale (GEB-50)"</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="an">author:</span><span class="co"> "Jaromir Gerhardt, Luisa Hautzinger, Theresa Knoch, Jako Spretz"</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> today</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a><span class="an">lang:</span><span class="co"> de</span></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a><span class="an">bibliography:</span><span class="co"> references.bib</span></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a><span class="an">csl:</span><span class="co"> apa.csl</span></span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a><span class="an">format:</span></span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a><span class="co">  html:</span></span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a><span class="co">    toc: true</span></span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a><span class="co">    toc-title: "Inhaltsverzeichnis"</span></span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a><span class="co">    theme: cosmo</span></span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a><span class="co">    code-fold: true</span></span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a><span class="co">    code-tools: true</span></span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a><span class="co">    number-sections: true</span></span>
<span id="cb11-17"><a href="#cb11-17" aria-hidden="true" tabindex="-1"></a><span class="co">    df-print: kable</span></span>
<span id="cb11-18"><a href="#cb11-18" aria-hidden="true" tabindex="-1"></a><span class="co">  pdf:</span></span>
<span id="cb11-19"><a href="#cb11-19" aria-hidden="true" tabindex="-1"></a><span class="co">    toc: false</span></span>
<span id="cb11-20"><a href="#cb11-20" aria-hidden="true" tabindex="-1"></a><span class="co">    number-sections: true</span></span>
<span id="cb11-21"><a href="#cb11-21" aria-hidden="true" tabindex="-1"></a><span class="co">    documentclass: scrartcl</span></span>
<span id="cb11-22"><a href="#cb11-22" aria-hidden="true" tabindex="-1"></a><span class="co">    geometry:</span></span>
<span id="cb11-23"><a href="#cb11-23" aria-hidden="true" tabindex="-1"></a><span class="co">      - top=18mm</span></span>
<span id="cb11-24"><a href="#cb11-24" aria-hidden="true" tabindex="-1"></a><span class="co">      - bottom=18mm</span></span>
<span id="cb11-25"><a href="#cb11-25" aria-hidden="true" tabindex="-1"></a><span class="co">      - left=20mm</span></span>
<span id="cb11-26"><a href="#cb11-26" aria-hidden="true" tabindex="-1"></a><span class="co">      - right=20mm</span></span>
<span id="cb11-27"><a href="#cb11-27" aria-hidden="true" tabindex="-1"></a><span class="co">    fontsize: 10pt</span></span>
<span id="cb11-28"><a href="#cb11-28" aria-hidden="true" tabindex="-1"></a><span class="co">    code-overflow: wrap</span></span>
<span id="cb11-29"><a href="#cb11-29" aria-hidden="true" tabindex="-1"></a><span class="co">    header-includes:</span></span>
<span id="cb11-30"><a href="#cb11-30" aria-hidden="true" tabindex="-1"></a><span class="co">      - \usepackage{etoolbox}</span></span>
<span id="cb11-31"><a href="#cb11-31" aria-hidden="true" tabindex="-1"></a><span class="co">      - \AtBeginEnvironment{verbatim}{\footnotesize}</span></span>
<span id="cb11-32"><a href="#cb11-32" aria-hidden="true" tabindex="-1"></a><span class="co">      - \AtBeginEnvironment{Highlighting}{\footnotesize}</span></span>
<span id="cb11-33"><a href="#cb11-33" aria-hidden="true" tabindex="-1"></a><span class="co">      - \AtBeginEnvironment{Shaded}{\vspace{-2pt}}</span></span>
<span id="cb11-34"><a href="#cb11-34" aria-hidden="true" tabindex="-1"></a><span class="an">execute:</span></span>
<span id="cb11-35"><a href="#cb11-35" aria-hidden="true" tabindex="-1"></a><span class="co">  echo: true</span></span>
<span id="cb11-36"><a href="#cb11-36" aria-hidden="true" tabindex="-1"></a><span class="co">  warning: false</span></span>
<span id="cb11-37"><a href="#cb11-37" aria-hidden="true" tabindex="-1"></a><span class="co">  message: false</span></span>
<span id="cb11-38"><a href="#cb11-38" aria-hidden="true" tabindex="-1"></a><span class="co">  eval: true</span></span>
<span id="cb11-39"><a href="#cb11-39" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb11-40"><a href="#cb11-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-43"><a href="#cb11-43" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb11-44"><a href="#cb11-44" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: setup</span></span>
<span id="cb11-45"><a href="#cb11-45" aria-hidden="true" tabindex="-1"></a><span class="co">#| include: false</span></span>
<span id="cb11-46"><a href="#cb11-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-47"><a href="#cb11-47" aria-hidden="true" tabindex="-1"></a><span class="co"># Pakete laden (wie in der Auswertungs-Datei)</span></span>
<span id="cb11-48"><a href="#cb11-48" aria-hidden="true" tabindex="-1"></a>librarian<span class="sc">::</span><span class="fu">shelf</span>(psych, eRm, car, labelled, dplyr, varhandle,</span>
<span id="cb11-49"><a href="#cb11-49" aria-hidden="true" tabindex="-1"></a>                 effectsize, lavaan)</span>
<span id="cb11-50"><a href="#cb11-50" aria-hidden="true" tabindex="-1"></a><span class="co"># psych  – KTT: alpha, omega, splitHalf, describe</span></span>
<span id="cb11-51"><a href="#cb11-51" aria-hidden="true" tabindex="-1"></a><span class="co"># eRm    – dichotomes Rasch-Modell (RM, person.parameter, SepRel)</span></span>
<span id="cb11-52"><a href="#cb11-52" aria-hidden="true" tabindex="-1"></a><span class="co"># lavaan – konfirmatorische Faktorenanalyse (CFA, WLSMV)</span></span>
<span id="cb11-53"><a href="#cb11-53" aria-hidden="true" tabindex="-1"></a><span class="co"># car    – Recodierung (recode); varhandle – unfactor</span></span>
<span id="cb11-54"><a href="#cb11-54" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb11-55"><a href="#cb11-55" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-56"><a href="#cb11-56" aria-hidden="true" tabindex="-1"></a><span class="fu"># Einleitung</span></span>
<span id="cb11-57"><a href="#cb11-57" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-58"><a href="#cb11-58" aria-hidden="true" tabindex="-1"></a><span class="fu">## Die Langform: GEB-50</span></span>
<span id="cb11-59"><a href="#cb11-59" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-60"><a href="#cb11-60" aria-hidden="true" tabindex="-1"></a>Die *General Ecological Behavior Scale* (GEB-50) von @kaiser2020geb misst die</span>
<span id="cb11-61"><a href="#cb11-61" aria-hidden="true" tabindex="-1"></a>individuelle Umwelteinstellung über selbstberichtetes ökologisches Verhalten.</span>
<span id="cb11-62"><a href="#cb11-62" aria-hidden="true" tabindex="-1"></a>Theoretische Grundlage ist das **Campbell-Paradigma**: Eine Einstellung zeigt</span>
<span id="cb11-63"><a href="#cb11-63" aria-hidden="true" tabindex="-1"></a>sich in den Verhaltenskosten, die eine Person bereit ist zu tragen, um ein</span>
<span id="cb11-64"><a href="#cb11-64" aria-hidden="true" tabindex="-1"></a>Einstellungsziel zu erreichen. Je kostenintensiver ein Verhalten (z. B. der</span>
<span id="cb11-65"><a href="#cb11-65" aria-hidden="true" tabindex="-1"></a>Verzicht auf ein Auto gegenüber dem Trennen von Altglas), desto stärker die</span>
<span id="cb11-66"><a href="#cb11-66" aria-hidden="true" tabindex="-1"></a>zugrunde liegende Umwelteinstellung.</span>
<span id="cb11-67"><a href="#cb11-67" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-68"><a href="#cb11-68" aria-hidden="true" tabindex="-1"></a>Die GEB-50 umfasst 50 Items aus **sechs Handlungsbereichen** – Energiesparen,</span>
<span id="cb11-69"><a href="#cb11-69" aria-hidden="true" tabindex="-1"></a>Mobilität, Abfallvermeiden, Konsum, Recycling und gesellschaftliches Engagement.</span>
<span id="cb11-70"><a href="#cb11-70" aria-hidden="true" tabindex="-1"></a>Sie wird über ein **eindimensionales Rasch-Modell** ausgewertet, sodass Personen-</span>
<span id="cb11-71"><a href="#cb11-71" aria-hidden="true" tabindex="-1"></a>und Itemparameter auf einer gemeinsamen latenten Dimension liegen und keine</span>
<span id="cb11-72"><a href="#cb11-72" aria-hidden="true" tabindex="-1"></a>Normierung erforderlich ist <span class="co">[</span><span class="ot">@kaiser2020geb</span><span class="co">]</span>. Die Vollversion erreicht eine</span>
<span id="cb11-73"><a href="#cb11-73" aria-hidden="true" tabindex="-1"></a>Separationsreliabilität von $rel = .71$ bis $.88$ <span class="co">[</span><span class="ot">@kaiser2020geb</span><span class="co">]</span>. Belege zur</span>
<span id="cb11-74"><a href="#cb11-74" aria-hidden="true" tabindex="-1"></a>Konstrukt- und Kriteriumsvalidität liegen vor: So korreliert die GEB-50 mit der</span>
<span id="cb11-75"><a href="#cb11-75" aria-hidden="true" tabindex="-1"></a>konstruktnahen NEP-Skala (*New Ecological Paradigm*) zu $r = .49$; die</span>
<span id="cb11-76"><a href="#cb11-76" aria-hidden="true" tabindex="-1"></a>prognostische Validität wurde u. a. in einer Untersuchung mit Autofahrer:innen</span>
<span id="cb11-77"><a href="#cb11-77" aria-hidden="true" tabindex="-1"></a>nachgewiesen <span class="co">[</span><span class="ot">@kaiser2020geb</span><span class="co">]</span>.</span>
<span id="cb11-78"><a href="#cb11-78" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-79"><a href="#cb11-79" aria-hidden="true" tabindex="-1"></a><span class="fu">## Motivation für eine Kurzform</span></span>
<span id="cb11-80"><a href="#cb11-80" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-81"><a href="#cb11-81" aria-hidden="true" tabindex="-1"></a>In vielen Anwendungskontexten – Interventionsstudien, wiederholte Messungen,</span>
<span id="cb11-82"><a href="#cb11-82" aria-hidden="true" tabindex="-1"></a>Online-Erhebungen mit knappem Zeitbudget – ist eine 50-Item-Skala unökonomisch.</span>
<span id="cb11-83"><a href="#cb11-83" aria-hidden="true" tabindex="-1"></a>Eine validierte **12-Item-Kurzform (GEB-12)** würde die Erhebungsdauer deutlich</span>
<span id="cb11-84"><a href="#cb11-84" aria-hidden="true" tabindex="-1"></a>senken und gleichzeitig die zentrale Eigenschaft der Langform – die Messung</span>
<span id="cb11-85"><a href="#cb11-85" aria-hidden="true" tabindex="-1"></a>einer einzelnen latenten Umwelteinstellung – erhalten.</span>
<span id="cb11-86"><a href="#cb11-86" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-87"><a href="#cb11-87" aria-hidden="true" tabindex="-1"></a>Eine Kurzform ist jedoch nicht einfach eine beliebige Item-Teilmenge.</span>
<span id="cb11-88"><a href="#cb11-88" aria-hidden="true" tabindex="-1"></a>@smith2000sins warnen ausdrücklich vor „Sünden" der Kurzformentwicklung: Eine</span>
<span id="cb11-89"><a href="#cb11-89" aria-hidden="true" tabindex="-1"></a>Kurzform muss eigenständig auf Reliabilität, faktorielle Struktur und</span>
<span id="cb11-90"><a href="#cb11-90" aria-hidden="true" tabindex="-1"></a>Konstruktvalidität gegenüber der Langform geprüft werden. Genau dieser Prüfung</span>
<span id="cb11-91"><a href="#cb11-91" aria-hidden="true" tabindex="-1"></a>folgt der vorliegende Bericht.</span>
<span id="cb11-92"><a href="#cb11-92" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-93"><a href="#cb11-93" aria-hidden="true" tabindex="-1"></a><span class="fu"># Methoden</span></span>
<span id="cb11-94"><a href="#cb11-94" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-95"><a href="#cb11-95" aria-hidden="true" tabindex="-1"></a><span class="fu">## Konstruktion der Kurzform</span></span>
<span id="cb11-96"><a href="#cb11-96" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-97"><a href="#cb11-97" aria-hidden="true" tabindex="-1"></a>Die Itemauswahl folgt einem theoriegeleiteten Verfahren in Anlehnung an</span>
<span id="cb11-98"><a href="#cb11-98" aria-hidden="true" tabindex="-1"></a>@smith2000sins und die Konstruktionslogik der Langform <span class="co">[</span><span class="ot">@kaiser2020geb</span><span class="co">]</span>:</span>
<span id="cb11-99"><a href="#cb11-99" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-100"><a href="#cb11-100" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>**Inhaltsvalidität:** Alle sechs Handlungsbereiche bleiben vertreten – je</span>
<span id="cb11-101"><a href="#cb11-101" aria-hidden="true" tabindex="-1"></a>   **ein leichtes** (geringe Verhaltenskosten) und **ein schweres** Item (hohe</span>
<span id="cb11-102"><a href="#cb11-102" aria-hidden="true" tabindex="-1"></a>   Verhaltenskosten) pro Bereich. Das ergibt $6 \times 2 = 12$ Items und sichert</span>
<span id="cb11-103"><a href="#cb11-103" aria-hidden="true" tabindex="-1"></a>   die inhaltliche Breite des Konstrukts.</span>
<span id="cb11-104"><a href="#cb11-104" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>**Schwierigkeitsverteilung:** Durch das Paar leicht/schwer wird der gesamte</span>
<span id="cb11-105"><a href="#cb11-105" aria-hidden="true" tabindex="-1"></a>   Bereich der Verhaltenskosten abgedeckt; Decken- und Bodeneffekte sollen</span>
<span id="cb11-106"><a href="#cb11-106" aria-hidden="true" tabindex="-1"></a>   vermieden werden (Ziel-Schwierigkeiten $P = .20$ bis $.80$).</span>
<span id="cb11-107"><a href="#cb11-107" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>**Trennschärfe:** Bevorzugt werden Items mit hoher Item-Total-Korrelation</span>
<span id="cb11-108"><a href="#cb11-108" aria-hidden="true" tabindex="-1"></a>   ($r_{it} &gt; .40$).</span>
<span id="cb11-109"><a href="#cb11-109" aria-hidden="true" tabindex="-1"></a><span class="ss">4. </span>**Rasch-Konformität:** Items sollen die Raschhomogenität der Langform erhalten.</span>
<span id="cb11-110"><a href="#cb11-110" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-111"><a href="#cb11-111" aria-hidden="true" tabindex="-1"></a>Die resultierende Itemauswahl (zwei Items je Bereich) ist in @tbl-items</span>
<span id="cb11-112"><a href="#cb11-112" aria-hidden="true" tabindex="-1"></a>dargestellt. </span>
<span id="cb11-113"><a href="#cb11-113" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-116"><a href="#cb11-116" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb11-117"><a href="#cb11-117" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: tbl-items</span></span>
<span id="cb11-118"><a href="#cb11-118" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb11-119"><a href="#cb11-119" aria-hidden="true" tabindex="-1"></a><span class="co">#| tbl-cap: "Itemauswahl der GEB-12 (je Bereich ein leichtes und ein schweres Item)"</span></span>
<span id="cb11-120"><a href="#cb11-120" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-121"><a href="#cb11-121" aria-hidden="true" tabindex="-1"></a>tibble<span class="sc">::</span><span class="fu">tribble</span>(</span>
<span id="cb11-122"><a href="#cb11-122" aria-hidden="true" tabindex="-1"></a>  <span class="sc">~</span>Bereich,                     <span class="sc">~</span><span class="st">`</span><span class="at">Leichtes Item (geringe Kosten)</span><span class="st">`</span>,                                              <span class="sc">~</span><span class="st">`</span><span class="at">Schweres Item (hohe Kosten)</span><span class="st">`</span>,</span>
<span id="cb11-123"><a href="#cb11-123" aria-hidden="true" tabindex="-1"></a>  <span class="st">"(1) Energiesparen"</span>,          <span class="st">"Ich warte, bis ich eine volle Wäschetrommel habe, bevor ich wasche. (Hfg.)"</span>,    <span class="st">"Ich beziehe Strom aus erneuerbarer Energie. (Ja/Nein)"</span>,</span>
<span id="cb11-124"><a href="#cb11-124" aria-hidden="true" tabindex="-1"></a>  <span class="st">"(2) Mobilität"</span>,              <span class="st">"Für den Arbeits-/Schulweg nutze ich Fahrrad, ÖPNV oder gehe zu Fuß. (Hfg.)"</span>,    <span class="st">"Ich verzichte auf ein Auto. (Ja/Nein)"</span>,</span>
<span id="cb11-125"><a href="#cb11-125" aria-hidden="true" tabindex="-1"></a>  <span class="st">"(3) Abfallvermeiden"</span>,        <span class="st">"Wenn ich im Geschäft eine Plastiktüte bekomme, nehme ich sie. (Hfg., neg.)"</span>,    <span class="st">"Ich verwende Einkaufstüten oder -taschen mehrfach. (Ja/Nein)"</span>,</span>
<span id="cb11-126"><a href="#cb11-126" aria-hidden="true" tabindex="-1"></a>  <span class="st">"(4) Konsum"</span>,                 <span class="st">"Ich benutze beim Waschen einen Weichspüler. (Hfg., neg.)"</span>,                     <span class="st">"Ich kaufe Obst und Gemüse der Jahreszeit entsprechend. (Hfg.)"</span>,</span>
<span id="cb11-127"><a href="#cb11-127" aria-hidden="true" tabindex="-1"></a>  <span class="st">"(5) Recycling"</span>,              <span class="st">"Altglas bringe ich zum Sammelcontainer. (Hfg.)"</span>,                               <span class="st">"Leere Batterien werfe ich in den Hausmüll. (Ja/Nein, neg.)"</span>,</span>
<span id="cb11-128"><a href="#cb11-128" aria-hidden="true" tabindex="-1"></a>  <span class="st">"(6) Ges. Engagement"</span>,        <span class="st">"Ich unterhalte mich mit Bekannten über Umweltverschmutzung &amp; Klimawandel. (Hfg.)"</span>, <span class="st">"Ich boykottiere Produkte von Firmen, die sich nachweislich umweltschädigend verhalten. (Ja/Nein)"</span></span>
<span id="cb11-129"><a href="#cb11-129" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb11-130"><a href="#cb11-130" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb11-131"><a href="#cb11-131" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-132"><a href="#cb11-132" aria-hidden="true" tabindex="-1"></a>::: {.callout-note}</span>
<span id="cb11-133"><a href="#cb11-133" aria-hidden="true" tabindex="-1"></a><span class="fu">## Antwortformat und Kodierung</span></span>
<span id="cb11-134"><a href="#cb11-134" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-135"><a href="#cb11-135" aria-hidden="true" tabindex="-1"></a>Wie in der Langform werden Häufigkeitsantworten (Hfg. ) **dichotomisiert**: *oft / sehr</span>
<span id="cb11-136"><a href="#cb11-136" aria-hidden="true" tabindex="-1"></a>oft* $\rightarrow 1$, *nie / selten / gelegentlich* $\rightarrow 0$</span>
<span id="cb11-137"><a href="#cb11-137" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">@kaiser2020geb</span><span class="co">]</span>. Negativ formulierte Items werden vor der Analyse umgepolt,</span>
<span id="cb11-138"><a href="#cb11-138" aria-hidden="true" tabindex="-1"></a>ja/nein-Items direkt übernommen. Die 12 Items mischen Häufigkeits- und</span>
<span id="cb11-139"><a href="#cb11-139" aria-hidden="true" tabindex="-1"></a>Ja/Nein-Format (gemischtes Modell).</span>
<span id="cb11-140"><a href="#cb11-140" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb11-141"><a href="#cb11-141" aria-hidden="true" tabindex="-1"></a><span class="fu">## Pretest: Funktion und statistische Einordnung {#sec-pretest}</span></span>
<span id="cb11-142"><a href="#cb11-142" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-143"><a href="#cb11-143" aria-hidden="true" tabindex="-1"></a>Vor der Hauptuntersuchung wurde ein **Pretest mit $N = 6$ Personen** durchgeführt.</span>
<span id="cb11-144"><a href="#cb11-144" aria-hidden="true" tabindex="-1"></a>Seine Funktion war ausschließlich die Prüfung von **Verständlichkeit und</span>
<span id="cb11-145"><a href="#cb11-145" aria-hidden="true" tabindex="-1"></a>Durchführbarkeit** des Fragebogens, nicht die Itemqualität. Bei dieser Fallzahl</span>
<span id="cb11-146"><a href="#cb11-146" aria-hidden="true" tabindex="-1"></a>sind Trennschärfen, Itemschwierigkeiten und Rasch-Parameter zu instabil für</span>
<span id="cb11-147"><a href="#cb11-147" aria-hidden="true" tabindex="-1"></a>verlässliche Entscheidungen; ein Itemaustausch auf dieser Basis hätte die</span>
<span id="cb11-148"><a href="#cb11-148" aria-hidden="true" tabindex="-1"></a>theoriegeleitete, balancierte Auswahl (je Bereich ein leichtes und ein schweres</span>
<span id="cb11-149"><a href="#cb11-149" aria-hidden="true" tabindex="-1"></a>Item) ohne echten Erkenntnisgewinn gefährdet. Da die Items zudem bereits aus der</span>
<span id="cb11-150"><a href="#cb11-150" aria-hidden="true" tabindex="-1"></a>rasch-skalierten, validierten Langform stammen und nach inhaltlichen sowie</span>
<span id="cb11-151"><a href="#cb11-151" aria-hidden="true" tabindex="-1"></a>psychometrischen Kriterien <span class="co">[</span><span class="ot">@smith2000sins</span><span class="co">]</span> ausgewählt wurden, war eine</span>
<span id="cb11-152"><a href="#cb11-152" aria-hidden="true" tabindex="-1"></a>empirische Vorab-Filterung an dieser Mini-Stichprobe nicht erforderlich.</span>
<span id="cb11-153"><a href="#cb11-153" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-154"><a href="#cb11-154" aria-hidden="true" tabindex="-1"></a>Die Pretest-Ergebnisse dienten daher **nur** der Sicherstellung von</span>
<span id="cb11-155"><a href="#cb11-155" aria-hidden="true" tabindex="-1"></a>Verständlichkeit und Durchführbarkeit. Alle berichteten psychometrischen</span>
<span id="cb11-156"><a href="#cb11-156" aria-hidden="true" tabindex="-1"></a>Prüfungen beruhen ausschließlich auf der **Haupterhebung** ($N = 60$).</span>
<span id="cb11-157"><a href="#cb11-157" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-158"><a href="#cb11-158" aria-hidden="true" tabindex="-1"></a><span class="fu">## Datenerhebung</span></span>
<span id="cb11-159"><a href="#cb11-159" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-160"><a href="#cb11-160" aria-hidden="true" tabindex="-1"></a>Die Datenerhebung erfolgte über die für wissenschaftliche Zwecke frei</span>
<span id="cb11-161"><a href="#cb11-161" aria-hidden="true" tabindex="-1"></a>verfügbare Online-Befragungsplattform **SoSci Survey**. Für die Originalversion</span>
<span id="cb11-162"><a href="#cb11-162" aria-hidden="true" tabindex="-1"></a>(GEB-50) und die entwickelte Kurzform wurden **zwei separate Fragebögen**</span>
<span id="cb11-163"><a href="#cb11-163" aria-hidden="true" tabindex="-1"></a>erstellt, die über einen individuellen Prüfcode miteinander verknüpft werden</span>
<span id="cb11-164"><a href="#cb11-164" aria-hidden="true" tabindex="-1"></a>konnten, sodass die Antworten jeder Person beiden Instrumenten zugeordnet werden</span>
<span id="cb11-165"><a href="#cb11-165" aria-hidden="true" tabindex="-1"></a>können.</span>
<span id="cb11-166"><a href="#cb11-166" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-167"><a href="#cb11-167" aria-hidden="true" tabindex="-1"></a>Das **GEB-50** umfasst 50 Items aus sechs Verhaltensdimensionen und besteht aus</span>
<span id="cb11-168"><a href="#cb11-168" aria-hidden="true" tabindex="-1"></a>zwei Teilen: einem ersten Teil mit Antworten auf einer **sechsstufigen</span>
<span id="cb11-169"><a href="#cb11-169" aria-hidden="true" tabindex="-1"></a>Likert-Skala** und einem zweiten Teil mit **dichotomen Items** (Antwortformat</span>
<span id="cb11-170"><a href="#cb11-170" aria-hidden="true" tabindex="-1"></a>„Ja"/„Nein"). Die entwickelte **Kurzform (GEB-12)** umfasst zwölf dichotome</span>
<span id="cb11-171"><a href="#cb11-171" aria-hidden="true" tabindex="-1"></a>Items („Ja"/„Nein"); aus jeder der sechs Dimensionen wurden zwei Items</span>
<span id="cb11-172"><a href="#cb11-172" aria-hidden="true" tabindex="-1"></a>ausgewählt.</span>
<span id="cb11-173"><a href="#cb11-173" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-174"><a href="#cb11-174" aria-hidden="true" tabindex="-1"></a>Die finale Datenerhebung erfolgte im Zeitraum vom **18.06. bis 28.06.2026**. Die</span>
<span id="cb11-175"><a href="#cb11-175" aria-hidden="true" tabindex="-1"></a>Stichprobe setzte sich aus Mitstudierenden sowie Personen aus dem privaten</span>
<span id="cb11-176"><a href="#cb11-176" aria-hidden="true" tabindex="-1"></a>Umfeld der Autor:innen zusammen und stellt somit eine **Gelegenheitsstichprobe**</span>
<span id="cb11-177"><a href="#cb11-177" aria-hidden="true" tabindex="-1"></a>dar. Angestrebt wurde eine Stichprobengröße von mindestens $N = 50$; nach</span>
<span id="cb11-178"><a href="#cb11-178" aria-hidden="true" tabindex="-1"></a>Ausschluss von Test- und Abbruchfällen umfasst die finale Auswertungsstichprobe</span>
<span id="cb11-179"><a href="#cb11-179" aria-hidden="true" tabindex="-1"></a>**$N = 60$** Personen (Kurz- und Langform jeweils 60).</span>
<span id="cb11-180"><a href="#cb11-180" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-181"><a href="#cb11-181" aria-hidden="true" tabindex="-1"></a>Die Auswahl der zwölf Items für die Kurzform erfolgte **vorrangig auf</span>
<span id="cb11-182"><a href="#cb11-182" aria-hidden="true" tabindex="-1"></a>theoretischer Grundlage**: Pro Handlungsbereich wurden zwei Items bestimmt – ein</span>
<span id="cb11-183"><a href="#cb11-183" aria-hidden="true" tabindex="-1"></a>leichtes und ein schweres –, sodass die sechs Dimensionen vollständig und mit</span>
<span id="cb11-184"><a href="#cb11-184" aria-hidden="true" tabindex="-1"></a>abgestufter Schwierigkeit abgebildet sind (siehe @sec-pretest sowie die</span>
<span id="cb11-185"><a href="#cb11-185" aria-hidden="true" tabindex="-1"></a>Konstruktionskriterien oben).</span>
<span id="cb11-186"><a href="#cb11-186" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-189"><a href="#cb11-189" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb11-190"><a href="#cb11-190" aria-hidden="true" tabindex="-1"></a><span class="do">#### load data frames ####</span></span>
<span id="cb11-191"><a href="#cb11-191" aria-hidden="true" tabindex="-1"></a>Data_S_raw <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"Data_S.csv"</span>, <span class="at">header =</span> <span class="cn">TRUE</span>, <span class="at">sep =</span> <span class="st">";"</span>,</span>
<span id="cb11-192"><a href="#cb11-192" aria-hidden="true" tabindex="-1"></a>                       <span class="at">check.names =</span> <span class="cn">FALSE</span>, <span class="at">fileEncoding =</span> <span class="st">"UCS-2LE"</span>)</span>
<span id="cb11-193"><a href="#cb11-193" aria-hidden="true" tabindex="-1"></a>Data_L_raw <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"Data_L.csv"</span>, <span class="at">header =</span> <span class="cn">TRUE</span>, <span class="at">sep =</span> <span class="st">";"</span>,</span>
<span id="cb11-194"><a href="#cb11-194" aria-hidden="true" tabindex="-1"></a>                       <span class="at">check.names =</span> <span class="cn">FALSE</span>, <span class="at">fileEncoding =</span> <span class="st">"UCS-2LE"</span>)</span>
<span id="cb11-195"><a href="#cb11-195" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-196"><a href="#cb11-196" aria-hidden="true" tabindex="-1"></a><span class="co"># Select cases</span></span>
<span id="cb11-197"><a href="#cb11-197" aria-hidden="true" tabindex="-1"></a>Data_S_raw <span class="ot">&lt;-</span> Data_S_raw[Data_S_raw<span class="sc">$</span>CASE <span class="sc">!=</span> <span class="dv">28</span> <span class="sc">&amp;</span> Data_S_raw<span class="sc">$</span>CASE <span class="sc">!=</span> <span class="dv">29</span></span>
<span id="cb11-198"><a href="#cb11-198" aria-hidden="true" tabindex="-1"></a>                     <span class="sc">&amp;</span> Data_S_raw<span class="sc">$</span>CASE <span class="sc">!=</span> <span class="dv">30</span> <span class="sc">&amp;</span> Data_S_raw<span class="sc">$</span>CASE <span class="sc">!=</span> <span class="dv">31</span></span>
<span id="cb11-199"><a href="#cb11-199" aria-hidden="true" tabindex="-1"></a>                     <span class="sc">&amp;</span> Data_S_raw<span class="sc">$</span>CASE <span class="sc">!=</span> <span class="dv">42</span> <span class="sc">&amp;</span> Data_S_raw<span class="sc">$</span>CASE <span class="sc">!=</span> <span class="dv">94</span></span>
<span id="cb11-200"><a href="#cb11-200" aria-hidden="true" tabindex="-1"></a>                     <span class="sc">&amp;</span> Data_S_raw<span class="sc">$</span>CASE <span class="sc">!=</span> <span class="dv">111</span>, ]</span>
<span id="cb11-201"><a href="#cb11-201" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-202"><a href="#cb11-202" aria-hidden="true" tabindex="-1"></a>Data_L_raw <span class="ot">&lt;-</span> Data_L_raw[Data_L_raw<span class="sc">$</span>CASE <span class="sc">!=</span> <span class="dv">130</span> <span class="sc">&amp;</span> Data_L_raw<span class="sc">$</span>CASE <span class="sc">!=</span> <span class="dv">153</span></span>
<span id="cb11-203"><a href="#cb11-203" aria-hidden="true" tabindex="-1"></a>                         <span class="sc">&amp;</span> Data_L_raw<span class="sc">$</span>CASE <span class="sc">!=</span> <span class="dv">155</span> <span class="sc">&amp;</span> Data_L_raw<span class="sc">$</span>CASE <span class="sc">!=</span> <span class="dv">156</span></span>
<span id="cb11-204"><a href="#cb11-204" aria-hidden="true" tabindex="-1"></a>                         <span class="sc">&amp;</span> Data_L_raw<span class="sc">$</span>CASE <span class="sc">!=</span> <span class="dv">159</span> <span class="sc">&amp;</span> Data_L_raw<span class="sc">$</span>CASE <span class="sc">!=</span> <span class="dv">164</span></span>
<span id="cb11-205"><a href="#cb11-205" aria-hidden="true" tabindex="-1"></a>                         <span class="sc">&amp;</span> Data_L_raw<span class="sc">$</span>CASE <span class="sc">!=</span> <span class="dv">173</span> <span class="sc">&amp;</span> Data_L_raw<span class="sc">$</span>CASE <span class="sc">!=</span> <span class="dv">175</span></span>
<span id="cb11-206"><a href="#cb11-206" aria-hidden="true" tabindex="-1"></a>                         <span class="sc">&amp;</span> Data_L_raw<span class="sc">$</span>CASE <span class="sc">!=</span> <span class="dv">182</span> <span class="sc">&amp;</span> Data_L_raw<span class="sc">$</span>CASE <span class="sc">!=</span> <span class="dv">196</span></span>
<span id="cb11-207"><a href="#cb11-207" aria-hidden="true" tabindex="-1"></a>                         <span class="sc">&amp;</span> Data_L_raw<span class="sc">$</span>CASE <span class="sc">!=</span> <span class="dv">215</span> <span class="sc">&amp;</span> Data_L_raw<span class="sc">$</span>CASE <span class="sc">!=</span> <span class="dv">224</span></span>
<span id="cb11-208"><a href="#cb11-208" aria-hidden="true" tabindex="-1"></a>                         <span class="sc">&amp;</span> Data_L_raw<span class="sc">$</span>CASE <span class="sc">!=</span> <span class="dv">237</span>, ]</span>
<span id="cb11-209"><a href="#cb11-209" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb11-210"><a href="#cb11-210" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-213"><a href="#cb11-213" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb11-214"><a href="#cb11-214" aria-hidden="true" tabindex="-1"></a><span class="do">## Short version (GEB-12)</span></span>
<span id="cb11-215"><a href="#cb11-215" aria-hidden="true" tabindex="-1"></a><span class="co"># select colums</span></span>
<span id="cb11-216"><a href="#cb11-216" aria-hidden="true" tabindex="-1"></a>Data_S <span class="ot">&lt;-</span> Data_S_raw <span class="sc">%&gt;%</span> <span class="fu">select</span>(KG01_01, KG01_02, KG01_03, KG01_04, KG01_05,</span>
<span id="cb11-217"><a href="#cb11-217" aria-hidden="true" tabindex="-1"></a>                                KG01_06, KG01_07, KG01_08, KG01_09, KG01_10,</span>
<span id="cb11-218"><a href="#cb11-218" aria-hidden="true" tabindex="-1"></a>                                KG01_11, KG01_12)</span>
<span id="cb11-219"><a href="#cb11-219" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-220"><a href="#cb11-220" aria-hidden="true" tabindex="-1"></a><span class="co"># Recode</span></span>
<span id="cb11-221"><a href="#cb11-221" aria-hidden="true" tabindex="-1"></a>Data_S <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">sapply</span>(Data_S[<span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">12</span>)], car<span class="sc">::</span>recode, <span class="st">"-1=0; 2=0; 1=1"</span>))</span>
<span id="cb11-222"><a href="#cb11-222" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-223"><a href="#cb11-223" aria-hidden="true" tabindex="-1"></a><span class="co"># Recode inverse items</span></span>
<span id="cb11-224"><a href="#cb11-224" aria-hidden="true" tabindex="-1"></a>Data_S[<span class="fu">c</span>(<span class="dv">10</span>)] <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">sapply</span>(Data_S[<span class="fu">c</span>(<span class="dv">10</span>)], car<span class="sc">::</span>recode, <span class="st">"0=1; 1=0"</span>))</span>
<span id="cb11-225"><a href="#cb11-225" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-226"><a href="#cb11-226" aria-hidden="true" tabindex="-1"></a><span class="do">## Long version (GEB-50)</span></span>
<span id="cb11-227"><a href="#cb11-227" aria-hidden="true" tabindex="-1"></a>Data_L <span class="ot">&lt;-</span> <span class="fu">unfactor</span>(Data_L_raw[<span class="dv">7</span><span class="sc">:</span><span class="dv">56</span>])</span>
<span id="cb11-228"><a href="#cb11-228" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-229"><a href="#cb11-229" aria-hidden="true" tabindex="-1"></a><span class="co"># Inverse dichotomous items</span></span>
<span id="cb11-230"><a href="#cb11-230" aria-hidden="true" tabindex="-1"></a>Data_L[<span class="fu">c</span>(<span class="dv">34</span>,<span class="dv">35</span>,<span class="dv">36</span>,<span class="dv">37</span>,<span class="dv">38</span>,<span class="dv">40</span>)] <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">sapply</span>(Data_L[<span class="fu">c</span>(<span class="dv">34</span>,<span class="dv">35</span>,<span class="dv">36</span>,<span class="dv">37</span>,<span class="dv">38</span>,<span class="dv">40</span>)],</span>
<span id="cb11-231"><a href="#cb11-231" aria-hidden="true" tabindex="-1"></a>                                                     car<span class="sc">::</span>recode, <span class="st">"1=2; 2=1"</span>))</span>
<span id="cb11-232"><a href="#cb11-232" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-233"><a href="#cb11-233" aria-hidden="true" tabindex="-1"></a><span class="co"># Recode dichotomous items</span></span>
<span id="cb11-234"><a href="#cb11-234" aria-hidden="true" tabindex="-1"></a>Data_L[<span class="fu">c</span>(<span class="dv">33</span><span class="sc">:</span><span class="dv">50</span>)] <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">sapply</span>(Data_L[<span class="fu">c</span>(<span class="dv">33</span><span class="sc">:</span><span class="dv">50</span>)], car<span class="sc">::</span>recode,</span>
<span id="cb11-235"><a href="#cb11-235" aria-hidden="true" tabindex="-1"></a>                                         <span class="st">"1=1; 2=0"</span>))</span>
<span id="cb11-236"><a href="#cb11-236" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-237"><a href="#cb11-237" aria-hidden="true" tabindex="-1"></a><span class="co"># Inverse polytomous items</span></span>
<span id="cb11-238"><a href="#cb11-238" aria-hidden="true" tabindex="-1"></a>Data_L[<span class="fu">c</span>(<span class="dv">3</span>,<span class="dv">4</span>,<span class="dv">6</span>,<span class="dv">7</span>,<span class="dv">10</span>,<span class="dv">17</span>,<span class="dv">18</span>,<span class="dv">23</span>,<span class="dv">26</span>,<span class="dv">27</span>,<span class="dv">28</span>,<span class="dv">29</span>,<span class="dv">31</span>)] <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(</span>
<span id="cb11-239"><a href="#cb11-239" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sapply</span>(Data_L[<span class="fu">c</span>(<span class="dv">3</span>,<span class="dv">4</span>,<span class="dv">6</span>,<span class="dv">7</span>,<span class="dv">10</span>,<span class="dv">17</span>,<span class="dv">18</span>,<span class="dv">23</span>,<span class="dv">26</span>,<span class="dv">27</span>,<span class="dv">28</span>,<span class="dv">29</span>,<span class="dv">31</span>)],</span>
<span id="cb11-240"><a href="#cb11-240" aria-hidden="true" tabindex="-1"></a>         car<span class="sc">::</span>recode,  <span class="st">"1=5; 2=4; 3=3; 4=2; 5=1"</span>))</span>
<span id="cb11-241"><a href="#cb11-241" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-242"><a href="#cb11-242" aria-hidden="true" tabindex="-1"></a><span class="co"># Dichotomize polytomous items</span></span>
<span id="cb11-243"><a href="#cb11-243" aria-hidden="true" tabindex="-1"></a>Data_L[<span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">32</span>)] <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">sapply</span>(Data_L[<span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">32</span>)], car<span class="sc">::</span>recode,</span>
<span id="cb11-244"><a href="#cb11-244" aria-hidden="true" tabindex="-1"></a>                                        <span class="st">"1=0; 2=0; 3=0; 4=1; 5=1"</span>))</span>
<span id="cb11-245"><a href="#cb11-245" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-246"><a href="#cb11-246" aria-hidden="true" tabindex="-1"></a><span class="co"># Data type -&gt; numeric</span></span>
<span id="cb11-247"><a href="#cb11-247" aria-hidden="true" tabindex="-1"></a>i <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">50</span>)</span>
<span id="cb11-248"><a href="#cb11-248" aria-hidden="true" tabindex="-1"></a>Data_L[, i] <span class="ot">&lt;-</span> <span class="fu">apply</span>(Data_L[, i], <span class="dv">2</span>, <span class="cf">function</span>(x) <span class="fu">as.numeric</span>(<span class="fu">as.character</span>(x)))</span>
<span id="cb11-249"><a href="#cb11-249" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb11-250"><a href="#cb11-250" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-251"><a href="#cb11-251" aria-hidden="true" tabindex="-1"></a><span class="fu">## Analyseplan</span></span>
<span id="cb11-252"><a href="#cb11-252" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-253"><a href="#cb11-253" aria-hidden="true" tabindex="-1"></a>Der Bericht prüft die Kurzform parallel zur Langform mit Verfahren der</span>
<span id="cb11-254"><a href="#cb11-254" aria-hidden="true" tabindex="-1"></a>klassischen Testtheorie (KTT) und der Item-Response-Theorie (IRT). Im Einzelnen:</span>
<span id="cb11-255"><a href="#cb11-255" aria-hidden="true" tabindex="-1"></a>deskriptive Statistik (Mittelwert, SD, Median der Personenscores), drei</span>
<span id="cb11-256"><a href="#cb11-256" aria-hidden="true" tabindex="-1"></a>Reliabilitätsschätzer – **Cronbachs $\alpha$**, **McDonalds $\omega$** (über die</span>
<span id="cb11-257"><a href="#cb11-257" aria-hidden="true" tabindex="-1"></a>sechs Handlungsbereiche) und **Split-Half-Reliabilität** –, die **Spearman-</span>
<span id="cb11-258"><a href="#cb11-258" aria-hidden="true" tabindex="-1"></a>Korrelation** der Summenscores von Kurz- und Langform, eine **konfirmatorische</span>
<span id="cb11-259"><a href="#cb11-259" aria-hidden="true" tabindex="-1"></a>Faktorenanalyse** des Sechs-Bereiche-Modells (WLSMV-Schätzer für dichotome</span>
<span id="cb11-260"><a href="#cb11-260" aria-hidden="true" tabindex="-1"></a>Items) sowie ein **dichotomes Rasch-Modell** (<span class="in">`eRm`</span>) mit Personenparametern und</span>
<span id="cb11-261"><a href="#cb11-261" aria-hidden="true" tabindex="-1"></a>Separationsreliabilität. Als Zielkriterien gelten $\alpha / \omega \geq .70$,</span>
<span id="cb11-262"><a href="#cb11-262" aria-hidden="true" tabindex="-1"></a>eine hohe Korrelation der Summenscores <span class="co">[</span><span class="ot">@smith2000sins</span><span class="co">]</span> sowie akzeptable CFA-Fitwerte (CFI $&gt; .95$, RMSEA $&lt; .06$, SRMR $&lt; .08$). Fit-Indizes sind dabei nur aussagekräftig, wenn das Modell stabil identifiziert ist; bei Schätzproblemen (Nicht-Konvergenz, unzulässige Parameter) werden sie nicht inhaltlich interpretiert.</span>
<span id="cb11-263"><a href="#cb11-263" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-264"><a href="#cb11-264" aria-hidden="true" tabindex="-1"></a><span class="fu"># Ergebnisse (klassische Testtheorie)</span></span>
<span id="cb11-265"><a href="#cb11-265" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-266"><a href="#cb11-266" aria-hidden="true" tabindex="-1"></a><span class="fu">## Deskriptive Statistik</span></span>
<span id="cb11-267"><a href="#cb11-267" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-268"><a href="#cb11-268" aria-hidden="true" tabindex="-1"></a>Zunächst werden Item- und Skalenkennwerte für Kurz- und Langform beschrieben.</span>
<span id="cb11-269"><a href="#cb11-269" aria-hidden="true" tabindex="-1"></a>@tbl-deskriptiv zeigt für jedes GEB-12-Item die Schwierigkeit $P$ (Anteil</span>
<span id="cb11-270"><a href="#cb11-270" aria-hidden="true" tabindex="-1"></a>zustimmender Antworten) und die part-whole-korrigierte Trennschärfe $r_{it}$,</span>
<span id="cb11-271"><a href="#cb11-271" aria-hidden="true" tabindex="-1"></a>ergänzt um eine Enschätzung.</span>
<span id="cb11-272"><a href="#cb11-272" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-275"><a href="#cb11-275" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb11-276"><a href="#cb11-276" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: tbl-deskriptiv</span></span>
<span id="cb11-277"><a href="#cb11-277" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb11-278"><a href="#cb11-278" aria-hidden="true" tabindex="-1"></a><span class="co">#| tbl-cap: "Itemkennwerte der GEB-12 (Schwierigkeit, Trennschärfe)"</span></span>
<span id="cb11-279"><a href="#cb11-279" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-280"><a href="#cb11-280" aria-hidden="true" tabindex="-1"></a><span class="co"># Itemstatistiken: mean = Itemschwierigkeit P (Mittelwert bei 0/1),</span></span>
<span id="cb11-281"><a href="#cb11-281" aria-hidden="true" tabindex="-1"></a><span class="co"># r.drop = part-whole-korrigierte Trennschaerfe</span></span>
<span id="cb11-282"><a href="#cb11-282" aria-hidden="true" tabindex="-1"></a>item_stats <span class="ot">&lt;-</span> psych<span class="sc">::</span><span class="fu">alpha</span>(Data_S, <span class="at">check.keys =</span> <span class="cn">TRUE</span>)<span class="sc">$</span>item.stats</span>
<span id="cb11-283"><a href="#cb11-283" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-284"><a href="#cb11-284" aria-hidden="true" tabindex="-1"></a><span class="co"># Ampel-Flags</span></span>
<span id="cb11-285"><a href="#cb11-285" aria-hidden="true" tabindex="-1"></a>flag_rit <span class="ot">&lt;-</span> <span class="cf">function</span>(r) dplyr<span class="sc">::</span><span class="fu">case_when</span>(</span>
<span id="cb11-286"><a href="#cb11-286" aria-hidden="true" tabindex="-1"></a>  r <span class="sc">&lt;</span> .<span class="dv">30</span>           <span class="sc">~</span> <span class="st">"kritisch"</span>,</span>
<span id="cb11-287"><a href="#cb11-287" aria-hidden="true" tabindex="-1"></a>  r <span class="sc">&lt;</span> .<span class="dv">40</span>           <span class="sc">~</span> <span class="st">"grenzwertig"</span>,</span>
<span id="cb11-288"><a href="#cb11-288" aria-hidden="true" tabindex="-1"></a>  <span class="cn">TRUE</span>              <span class="sc">~</span> <span class="st">"ok"</span></span>
<span id="cb11-289"><a href="#cb11-289" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb11-290"><a href="#cb11-290" aria-hidden="true" tabindex="-1"></a>flag_p <span class="ot">&lt;-</span> <span class="cf">function</span>(p) dplyr<span class="sc">::</span><span class="fu">case_when</span>(</span>
<span id="cb11-291"><a href="#cb11-291" aria-hidden="true" tabindex="-1"></a>  p <span class="sc">&lt;</span> .<span class="dv">20</span> <span class="sc">|</span> p <span class="sc">&gt;</span> .<span class="dv">80</span> <span class="sc">~</span> <span class="st">"Decken/Boden"</span>,</span>
<span id="cb11-292"><a href="#cb11-292" aria-hidden="true" tabindex="-1"></a>  <span class="cn">TRUE</span>              <span class="sc">~</span> <span class="st">"ok"</span></span>
<span id="cb11-293"><a href="#cb11-293" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb11-294"><a href="#cb11-294" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-295"><a href="#cb11-295" aria-hidden="true" tabindex="-1"></a>item_stats <span class="sc">|&gt;</span></span>
<span id="cb11-296"><a href="#cb11-296" aria-hidden="true" tabindex="-1"></a>  tibble<span class="sc">::</span><span class="fu">rownames_to_column</span>(<span class="st">"Item"</span>) <span class="sc">|&gt;</span></span>
<span id="cb11-297"><a href="#cb11-297" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">transmute</span>(</span>
<span id="cb11-298"><a href="#cb11-298" aria-hidden="true" tabindex="-1"></a>    Item,</span>
<span id="cb11-299"><a href="#cb11-299" aria-hidden="true" tabindex="-1"></a>    <span class="at">Schwierigkeit_P   =</span> <span class="fu">round</span>(mean, <span class="dv">2</span>),</span>
<span id="cb11-300"><a href="#cb11-300" aria-hidden="true" tabindex="-1"></a>    <span class="at">Bewertung_P       =</span> <span class="fu">flag_p</span>(mean),</span>
<span id="cb11-301"><a href="#cb11-301" aria-hidden="true" tabindex="-1"></a>    <span class="at">Trennschaerfe_rit =</span> <span class="fu">round</span>(r.drop, <span class="dv">2</span>),</span>
<span id="cb11-302"><a href="#cb11-302" aria-hidden="true" tabindex="-1"></a>    <span class="at">Bewertung_rit     =</span> <span class="fu">flag_rit</span>(r.drop)</span>
<span id="cb11-303"><a href="#cb11-303" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb11-304"><a href="#cb11-304" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb11-305"><a href="#cb11-305" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-308"><a href="#cb11-308" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb11-309"><a href="#cb11-309" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: deskriptiv-score</span></span>
<span id="cb11-310"><a href="#cb11-310" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-311"><a href="#cb11-311" aria-hidden="true" tabindex="-1"></a><span class="co"># Personen-Mittelwerte (Mittelwert, SD, Median) je Skala</span></span>
<span id="cb11-312"><a href="#cb11-312" aria-hidden="true" tabindex="-1"></a>Data_S_Mean <span class="ot">&lt;-</span> <span class="fu">rowMeans</span>(Data_S, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb11-313"><a href="#cb11-313" aria-hidden="true" tabindex="-1"></a>Data_L_Mean <span class="ot">&lt;-</span> <span class="fu">rowMeans</span>(Data_L, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb11-314"><a href="#cb11-314" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-315"><a href="#cb11-315" aria-hidden="true" tabindex="-1"></a>psych<span class="sc">::</span><span class="fu">describe</span>(Data_S_Mean)   <span class="co"># GEB-12</span></span>
<span id="cb11-316"><a href="#cb11-316" aria-hidden="true" tabindex="-1"></a>psych<span class="sc">::</span><span class="fu">describe</span>(Data_L_Mean)   <span class="co"># GEB-50</span></span>
<span id="cb11-317"><a href="#cb11-317" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb11-318"><a href="#cb11-318" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-319"><a href="#cb11-319" aria-hidden="true" tabindex="-1"></a><span class="fu">## Reliabilität: Alpha, Omega und Split-Half</span></span>
<span id="cb11-320"><a href="#cb11-320" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-321"><a href="#cb11-321" aria-hidden="true" tabindex="-1"></a>Berichtet werden drei Reliabilitätsschätzer, jeweils für Kurz- und Langform.</span>
<span id="cb11-322"><a href="#cb11-322" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-325"><a href="#cb11-325" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb11-326"><a href="#cb11-326" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: reliabilitaet</span></span>
<span id="cb11-327"><a href="#cb11-327" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: true</span></span>
<span id="cb11-328"><a href="#cb11-328" aria-hidden="true" tabindex="-1"></a><span class="co">#| eval: true</span></span>
<span id="cb11-329"><a href="#cb11-329" aria-hidden="true" tabindex="-1"></a><span class="co">#| results: "hide"</span></span>
<span id="cb11-330"><a href="#cb11-330" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-331"><a href="#cb11-331" aria-hidden="true" tabindex="-1"></a><span class="do">#### Cronbachs Alpha ####</span></span>
<span id="cb11-332"><a href="#cb11-332" aria-hidden="true" tabindex="-1"></a>psych<span class="sc">::</span><span class="fu">alpha</span>(Data_S, <span class="at">check.keys =</span> <span class="cn">TRUE</span>)   <span class="co"># GEB-12</span></span>
<span id="cb11-333"><a href="#cb11-333" aria-hidden="true" tabindex="-1"></a>psych<span class="sc">::</span><span class="fu">alpha</span>(Data_L, <span class="at">check.keys =</span> <span class="cn">TRUE</span>)   <span class="co"># GEB-50</span></span>
<span id="cb11-334"><a href="#cb11-334" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-335"><a href="#cb11-335" aria-hidden="true" tabindex="-1"></a><span class="do">#### McDonalds Omega ueber die sechs Handlungsbereiche ####</span></span>
<span id="cb11-336"><a href="#cb11-336" aria-hidden="true" tabindex="-1"></a>psych<span class="sc">::</span><span class="fu">omega</span>(Data_S, <span class="at">nfactors =</span> <span class="dv">6</span>, <span class="at">plot =</span> <span class="cn">FALSE</span>)        <span class="co"># GEB-12</span></span>
<span id="cb11-337"><a href="#cb11-337" aria-hidden="true" tabindex="-1"></a>psych<span class="sc">::</span><span class="fu">omega</span>(Data_L, <span class="at">nfactors =</span> <span class="dv">6</span>, <span class="at">plot =</span> <span class="cn">FALSE</span>)        <span class="co"># GEB-50</span></span>
<span id="cb11-338"><a href="#cb11-338" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-339"><a href="#cb11-339" aria-hidden="true" tabindex="-1"></a><span class="do">#### Split-Half-Reliabilitaet ####</span></span>
<span id="cb11-340"><a href="#cb11-340" aria-hidden="true" tabindex="-1"></a><span class="fu">splitHalf</span>(Data_S)                         <span class="co"># GEB-12</span></span>
<span id="cb11-341"><a href="#cb11-341" aria-hidden="true" tabindex="-1"></a><span class="fu">splitHalf</span>(Data_L)                         <span class="co"># GEB-50</span></span>
<span id="cb11-342"><a href="#cb11-342" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb11-343"><a href="#cb11-343" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-346"><a href="#cb11-346" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb11-347"><a href="#cb11-347" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: reliabilitaet_table</span></span>
<span id="cb11-348"><a href="#cb11-348" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo : false</span></span>
<span id="cb11-349"><a href="#cb11-349" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-350"><a href="#cb11-350" aria-hidden="true" tabindex="-1"></a><span class="co"># Kennwerte berechnen und in Objekte speichern (keine langen Ausgaben)</span></span>
<span id="cb11-351"><a href="#cb11-351" aria-hidden="true" tabindex="-1"></a>a_S  <span class="ot">&lt;-</span> psych<span class="sc">::</span><span class="fu">alpha</span>(Data_S, <span class="at">check.keys =</span> <span class="cn">TRUE</span>)<span class="sc">$</span>total<span class="sc">$</span>raw_alpha</span>
<span id="cb11-352"><a href="#cb11-352" aria-hidden="true" tabindex="-1"></a>a_L  <span class="ot">&lt;-</span> psych<span class="sc">::</span><span class="fu">alpha</span>(Data_L, <span class="at">check.keys =</span> <span class="cn">TRUE</span>)<span class="sc">$</span>total<span class="sc">$</span>raw_alpha</span>
<span id="cb11-353"><a href="#cb11-353" aria-hidden="true" tabindex="-1"></a>o_S  <span class="ot">&lt;-</span> psych<span class="sc">::</span><span class="fu">omega</span>(Data_S, <span class="at">nfactors =</span> <span class="dv">6</span>, <span class="at">plot =</span> <span class="cn">FALSE</span>)<span class="sc">$</span>omega.tot</span>
<span id="cb11-354"><a href="#cb11-354" aria-hidden="true" tabindex="-1"></a>o_L  <span class="ot">&lt;-</span> psych<span class="sc">::</span><span class="fu">omega</span>(Data_L, <span class="at">nfactors =</span> <span class="dv">6</span>, <span class="at">plot =</span> <span class="cn">FALSE</span>)<span class="sc">$</span>omega.tot</span>
<span id="cb11-355"><a href="#cb11-355" aria-hidden="true" tabindex="-1"></a>sh_S <span class="ot">&lt;-</span> psych<span class="sc">::</span><span class="fu">splitHalf</span>(Data_S)<span class="sc">$</span>meanr</span>
<span id="cb11-356"><a href="#cb11-356" aria-hidden="true" tabindex="-1"></a>sh_L <span class="ot">&lt;-</span> psych<span class="sc">::</span><span class="fu">splitHalf</span>(Data_L)<span class="sc">$</span>meanr</span>
<span id="cb11-357"><a href="#cb11-357" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-358"><a href="#cb11-358" aria-hidden="true" tabindex="-1"></a><span class="co"># Kompakte Ergebnis-Tabelle</span></span>
<span id="cb11-359"><a href="#cb11-359" aria-hidden="true" tabindex="-1"></a>tibble<span class="sc">::</span><span class="fu">tibble</span>(</span>
<span id="cb11-360"><a href="#cb11-360" aria-hidden="true" tabindex="-1"></a>  <span class="at">Skala           =</span> <span class="fu">c</span>(<span class="st">"GEB-12 (Kurzform)"</span>, <span class="st">"GEB-50 (Langform)"</span>),</span>
<span id="cb11-361"><a href="#cb11-361" aria-hidden="true" tabindex="-1"></a>  <span class="at">Cronbachs_Alpha =</span> <span class="fu">round</span>(<span class="fu">c</span>(a_S, a_L), <span class="dv">2</span>),</span>
<span id="cb11-362"><a href="#cb11-362" aria-hidden="true" tabindex="-1"></a>  <span class="at">Omega_total     =</span> <span class="fu">round</span>(<span class="fu">c</span>(o_S, o_L), <span class="dv">2</span>),</span>
<span id="cb11-363"><a href="#cb11-363" aria-hidden="true" tabindex="-1"></a>  <span class="at">Split_Half_mean =</span> <span class="fu">round</span>(<span class="fu">c</span>(sh_S, sh_L), <span class="dv">2</span>)</span>
<span id="cb11-364"><a href="#cb11-364" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb11-365"><a href="#cb11-365" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb11-366"><a href="#cb11-366" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-367"><a href="#cb11-367" aria-hidden="true" tabindex="-1"></a>::: {.callout-tip}</span>
<span id="cb11-368"><a href="#cb11-368" aria-hidden="true" tabindex="-1"></a><span class="fu">## Maßstab und Befund</span></span>
<span id="cb11-369"><a href="#cb11-369" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-370"><a href="#cb11-370" aria-hidden="true" tabindex="-1"></a>Als Zielwert gilt $\alpha \geq .70$. Eine **Reduktion** gegenüber der</span>
<span id="cb11-371"><a href="#cb11-371" aria-hidden="true" tabindex="-1"></a>Separationsreliabilität der Vollversion ($.71$–$.88$) wäre angesichts der starken</span>
<span id="cb11-372"><a href="#cb11-372" aria-hidden="true" tabindex="-1"></a>Kürzung erwartbar und solange unkritisch, wie $.70$ erreicht wird. Tatsächlich</span>
<span id="cb11-373"><a href="#cb11-373" aria-hidden="true" tabindex="-1"></a>verfehlt die GEB-12 dieses Kriterium mit $\alpha = .50$ (Split-Half $.47$) jedoch</span>
<span id="cb11-374"><a href="#cb11-374" aria-hidden="true" tabindex="-1"></a>deutlich, während die Langform mit $\alpha = .87$ klar darüber liegt. Der Wert</span>
<span id="cb11-375"><a href="#cb11-375" aria-hidden="true" tabindex="-1"></a>Omega total $= .72$ ist wegen Überparametrisierung (sechs Faktoren, zwölf Items)</span>
<span id="cb11-376"><a href="#cb11-376" aria-hidden="true" tabindex="-1"></a>nicht belastbar.</span>
<span id="cb11-377"><a href="#cb11-377" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb11-378"><a href="#cb11-378" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-379"><a href="#cb11-379" aria-hidden="true" tabindex="-1"></a><span class="fu">## Korrelation Kurzform vs. Langform</span></span>
<span id="cb11-380"><a href="#cb11-380" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-381"><a href="#cb11-381" aria-hidden="true" tabindex="-1"></a>Das Kernkriterium der Konstruktvalidität nach @smith2000sins ist die</span>
<span id="cb11-382"><a href="#cb11-382" aria-hidden="true" tabindex="-1"></a>Übereinstimmung der Personenwerte beider Formen.</span>
<span id="cb11-383"><a href="#cb11-383" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-386"><a href="#cb11-386" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb11-387"><a href="#cb11-387" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fig-korrelation</span></span>
<span id="cb11-388"><a href="#cb11-388" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Zusammenhang der Summenscores von GEB-12 und GEB-50"</span></span>
<span id="cb11-389"><a href="#cb11-389" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb11-390"><a href="#cb11-390" aria-hidden="true" tabindex="-1"></a><span class="do">### Bravais pearson correlation ####</span></span>
<span id="cb11-391"><a href="#cb11-391" aria-hidden="true" tabindex="-1"></a>Sum_L <span class="ot">&lt;-</span> <span class="fu">rowSums</span>(Data_L, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)   <span class="co"># GEB-50</span></span>
<span id="cb11-392"><a href="#cb11-392" aria-hidden="true" tabindex="-1"></a>Sum_S <span class="ot">&lt;-</span> <span class="fu">rowSums</span>(Data_S, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)   <span class="co"># GEB-12</span></span>
<span id="cb11-393"><a href="#cb11-393" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-394"><a href="#cb11-394" aria-hidden="true" tabindex="-1"></a><span class="co"># Spearman-Rangkorrelation</span></span>
<span id="cb11-395"><a href="#cb11-395" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(Sum_L, Sum_S, <span class="at">method =</span> <span class="st">"spearman"</span>)</span>
<span id="cb11-396"><a href="#cb11-396" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb11-399"><a href="#cb11-399" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb11-400"><a href="#cb11-400" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb11-401"><a href="#cb11-401" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-402"><a href="#cb11-402" aria-hidden="true" tabindex="-1"></a><span class="co"># Kompakte Tabelle: zentrale Kennwerte der Korrelationsprüfung</span></span>
<span id="cb11-403"><a href="#cb11-403" aria-hidden="true" tabindex="-1"></a>rho <span class="ot">&lt;-</span> <span class="fu">cor</span>(Sum_L, Sum_S, <span class="at">method =</span> <span class="st">"spearman"</span>)</span>
<span id="cb11-404"><a href="#cb11-404" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-405"><a href="#cb11-405" aria-hidden="true" tabindex="-1"></a>tibble<span class="sc">::</span><span class="fu">tibble</span>(</span>
<span id="cb11-406"><a href="#cb11-406" aria-hidden="true" tabindex="-1"></a>  <span class="at">Kennwert =</span> <span class="fu">c</span>(<span class="st">"N"</span>, <span class="st">"Spearman-Rho (GEB-50 x GEB-12)"</span>,</span>
<span id="cb11-407"><a href="#cb11-407" aria-hidden="true" tabindex="-1"></a>               <span class="st">"Mittelwert Summenscore GEB-50"</span>, <span class="st">"Mittelwert Summenscore GEB-12"</span>),</span>
<span id="cb11-408"><a href="#cb11-408" aria-hidden="true" tabindex="-1"></a>  <span class="at">Wert =</span> <span class="fu">c</span>(<span class="fu">length</span>(Sum_S),</span>
<span id="cb11-409"><a href="#cb11-409" aria-hidden="true" tabindex="-1"></a>           <span class="fu">round</span>(rho, <span class="dv">2</span>),</span>
<span id="cb11-410"><a href="#cb11-410" aria-hidden="true" tabindex="-1"></a>           <span class="fu">round</span>(<span class="fu">mean</span>(Sum_L), <span class="dv">1</span>),</span>
<span id="cb11-411"><a href="#cb11-411" aria-hidden="true" tabindex="-1"></a>           <span class="fu">round</span>(<span class="fu">mean</span>(Sum_S), <span class="dv">1</span>))</span>
<span id="cb11-412"><a href="#cb11-412" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb11-413"><a href="#cb11-413" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb11-414"><a href="#cb11-414" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-415"><a href="#cb11-415" aria-hidden="true" tabindex="-1"></a>Eine hohe Korrelation würde belegen, dass die Kurzform die Personenordnung der</span>
<span id="cb11-416"><a href="#cb11-416" aria-hidden="true" tabindex="-1"></a>Langform weitgehend reproduziert. Mit $\rho = .30$ besteht jedoch nur ein</span>
<span id="cb11-417"><a href="#cb11-417" aria-hidden="true" tabindex="-1"></a>mittlerer Zusammenhang, der deutlich unter dem für eine valide Kurzform</span>
<span id="cb11-418"><a href="#cb11-418" aria-hidden="true" tabindex="-1"></a>erwartbaren Niveau liegt. Dabei ist zu beachten, dass dieser Wert die</span>
<span id="cb11-419"><a href="#cb11-419" aria-hidden="true" tabindex="-1"></a>Übereinstimmung sogar noch **überschätzt**: Die zwölf Items sind in der Langform</span>
<span id="cb11-420"><a href="#cb11-420" aria-hidden="true" tabindex="-1"></a>enthalten (Item-Overlap), und die niedrige Reliabilität der Kurzform</span>
<span id="cb11-421"><a href="#cb11-421" aria-hidden="true" tabindex="-1"></a>($\alpha = .50$) deckelt die maximal erreichbare Korrelation rechnerisch nach</span>
<span id="cb11-422"><a href="#cb11-422" aria-hidden="true" tabindex="-1"></a>oben – ein klassischer Effekt im Sinne von @smith2000sins.</span>
<span id="cb11-423"><a href="#cb11-423" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-424"><a href="#cb11-424" aria-hidden="true" tabindex="-1"></a><span class="fu"># Ergebnisse (Faktorstruktur und IRT)</span></span>
<span id="cb11-425"><a href="#cb11-425" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-426"><a href="#cb11-426" aria-hidden="true" tabindex="-1"></a><span class="fu">## Konfirmatorische Faktorenanalyse</span></span>
<span id="cb11-427"><a href="#cb11-427" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-428"><a href="#cb11-428" aria-hidden="true" tabindex="-1"></a>Geprüft wird die faktorielle Struktur der GEB-12 über ein **Sechs-Faktoren-</span>
<span id="cb11-429"><a href="#cb11-429" aria-hidden="true" tabindex="-1"></a>Modell**, das die sechs Handlungsbereiche als latente Faktoren mit je zwei</span>
<span id="cb11-430"><a href="#cb11-430" aria-hidden="true" tabindex="-1"></a>Indikatoren abbildet. Da die Items dichotom sind, wird der Schätzer <span class="in">`WLSMV`</span> mit</span>
<span id="cb11-431"><a href="#cb11-431" aria-hidden="true" tabindex="-1"></a>Deklaration der Items als <span class="in">`ordered`</span> verwendet.</span>
<span id="cb11-432"><a href="#cb11-432" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-435"><a href="#cb11-435" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb11-436"><a href="#cb11-436" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: true</span></span>
<span id="cb11-437"><a href="#cb11-437" aria-hidden="true" tabindex="-1"></a><span class="co">#| eval: false</span></span>
<span id="cb11-438"><a href="#cb11-438" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb11-439"><a href="#cb11-439" aria-hidden="true" tabindex="-1"></a><span class="do">#### CFA_Model ####</span></span>
<span id="cb11-440"><a href="#cb11-440" aria-hidden="true" tabindex="-1"></a><span class="co"># Sechs-Faktoren-Modell (je Handlungsbereich ein Faktor mit 2 Items)</span></span>
<span id="cb11-441"><a href="#cb11-441" aria-hidden="true" tabindex="-1"></a>CFA_model <span class="ot">&lt;-</span> <span class="st">'</span></span>
<span id="cb11-442"><a href="#cb11-442" aria-hidden="true" tabindex="-1"></a><span class="st">Energiesparen =~ KG01_01 + KG01_02</span></span>
<span id="cb11-443"><a href="#cb11-443" aria-hidden="true" tabindex="-1"></a><span class="st">Mobilität =~ KG01_03 + KG01_04</span></span>
<span id="cb11-444"><a href="#cb11-444" aria-hidden="true" tabindex="-1"></a><span class="st">Abfallvermeiden =~ KG01_05 + KG01_06</span></span>
<span id="cb11-445"><a href="#cb11-445" aria-hidden="true" tabindex="-1"></a><span class="st">Konsum =~ KG01_07 + KG01_08</span></span>
<span id="cb11-446"><a href="#cb11-446" aria-hidden="true" tabindex="-1"></a><span class="st">Recycling =~ KG01_09 + KG01_10</span></span>
<span id="cb11-447"><a href="#cb11-447" aria-hidden="true" tabindex="-1"></a><span class="st">Engagement =~ KG01_11 + KG01_12</span></span>
<span id="cb11-448"><a href="#cb11-448" aria-hidden="true" tabindex="-1"></a><span class="st">'</span></span>
<span id="cb11-449"><a href="#cb11-449" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-450"><a href="#cb11-450" aria-hidden="true" tabindex="-1"></a>lavaan<span class="sc">::</span><span class="fu">cfa</span>(CFA_model, <span class="at">data =</span> Data_S)</span>
<span id="cb11-451"><a href="#cb11-451" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-452"><a href="#cb11-452" aria-hidden="true" tabindex="-1"></a>Items_S <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"KG01_01"</span>, <span class="st">"KG01_02"</span>,</span>
<span id="cb11-453"><a href="#cb11-453" aria-hidden="true" tabindex="-1"></a>  <span class="st">"KG01_03"</span>, <span class="st">"KG01_04"</span>,</span>
<span id="cb11-454"><a href="#cb11-454" aria-hidden="true" tabindex="-1"></a>  <span class="st">"KG01_05"</span>, <span class="st">"KG01_06"</span>,</span>
<span id="cb11-455"><a href="#cb11-455" aria-hidden="true" tabindex="-1"></a>  <span class="st">"KG01_07"</span>, <span class="st">"KG01_08"</span>,</span>
<span id="cb11-456"><a href="#cb11-456" aria-hidden="true" tabindex="-1"></a>  <span class="st">"KG01_09"</span>, <span class="st">"KG01_10"</span>,</span>
<span id="cb11-457"><a href="#cb11-457" aria-hidden="true" tabindex="-1"></a>  <span class="st">"KG01_11"</span>, <span class="st">"KG01_12"</span>)</span>
<span id="cb11-458"><a href="#cb11-458" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-459"><a href="#cb11-459" aria-hidden="true" tabindex="-1"></a>Fit <span class="ot">&lt;-</span> <span class="fu">cfa</span>(CFA_model, <span class="at">data =</span> Data_S,</span>
<span id="cb11-460"><a href="#cb11-460" aria-hidden="true" tabindex="-1"></a>                   <span class="at">ordered =</span> Items_S, <span class="at">estimator =</span> <span class="st">"WLSMV"</span>)</span>
<span id="cb11-461"><a href="#cb11-461" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-462"><a href="#cb11-462" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(Fit, <span class="at">fit.measures =</span> <span class="cn">TRUE</span>, <span class="at">standardized =</span> <span class="cn">TRUE</span>)</span>
<span id="cb11-463"><a href="#cb11-463" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb11-466"><a href="#cb11-466" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb11-467"><a href="#cb11-467" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb11-468"><a href="#cb11-468" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-469"><a href="#cb11-469" aria-hidden="true" tabindex="-1"></a>CFA_model <span class="ot">&lt;-</span> <span class="st">'</span></span>
<span id="cb11-470"><a href="#cb11-470" aria-hidden="true" tabindex="-1"></a><span class="st">Energiesparen =~ KG01_01 + KG01_02</span></span>
<span id="cb11-471"><a href="#cb11-471" aria-hidden="true" tabindex="-1"></a><span class="st">Mobilität =~ KG01_03 + KG01_04</span></span>
<span id="cb11-472"><a href="#cb11-472" aria-hidden="true" tabindex="-1"></a><span class="st">Abfallvermeiden =~ KG01_05 + KG01_06</span></span>
<span id="cb11-473"><a href="#cb11-473" aria-hidden="true" tabindex="-1"></a><span class="st">Konsum =~ KG01_07 + KG01_08</span></span>
<span id="cb11-474"><a href="#cb11-474" aria-hidden="true" tabindex="-1"></a><span class="st">Recycling =~ KG01_09 + KG01_10</span></span>
<span id="cb11-475"><a href="#cb11-475" aria-hidden="true" tabindex="-1"></a><span class="st">Engagement =~ KG01_11 + KG01_12</span></span>
<span id="cb11-476"><a href="#cb11-476" aria-hidden="true" tabindex="-1"></a><span class="st">'</span></span>
<span id="cb11-477"><a href="#cb11-477" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-478"><a href="#cb11-478" aria-hidden="true" tabindex="-1"></a>Items_S <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"KG01_01"</span>, <span class="st">"KG01_02"</span>,</span>
<span id="cb11-479"><a href="#cb11-479" aria-hidden="true" tabindex="-1"></a>  <span class="st">"KG01_03"</span>, <span class="st">"KG01_04"</span>,</span>
<span id="cb11-480"><a href="#cb11-480" aria-hidden="true" tabindex="-1"></a>  <span class="st">"KG01_05"</span>, <span class="st">"KG01_06"</span>,</span>
<span id="cb11-481"><a href="#cb11-481" aria-hidden="true" tabindex="-1"></a>  <span class="st">"KG01_07"</span>, <span class="st">"KG01_08"</span>,</span>
<span id="cb11-482"><a href="#cb11-482" aria-hidden="true" tabindex="-1"></a>  <span class="st">"KG01_09"</span>, <span class="st">"KG01_10"</span>,</span>
<span id="cb11-483"><a href="#cb11-483" aria-hidden="true" tabindex="-1"></a>  <span class="st">"KG01_11"</span>, <span class="st">"KG01_12"</span>)</span>
<span id="cb11-484"><a href="#cb11-484" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-485"><a href="#cb11-485" aria-hidden="true" tabindex="-1"></a>Fit <span class="ot">&lt;-</span> <span class="fu">cfa</span>(CFA_model, <span class="at">data =</span> Data_S,</span>
<span id="cb11-486"><a href="#cb11-486" aria-hidden="true" tabindex="-1"></a>                   <span class="at">ordered =</span> Items_S, <span class="at">estimator =</span> <span class="st">"WLSMV"</span>)</span>
<span id="cb11-487"><a href="#cb11-487" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-488"><a href="#cb11-488" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(lavaan<span class="sc">::</span><span class="fu">fitMeasures</span>(</span>
<span id="cb11-489"><a href="#cb11-489" aria-hidden="true" tabindex="-1"></a>  Fit, <span class="fu">c</span>(<span class="st">"chisq.scaled"</span>, <span class="st">"df"</span>, <span class="st">"pvalue.scaled"</span>,</span>
<span id="cb11-490"><a href="#cb11-490" aria-hidden="true" tabindex="-1"></a>         <span class="st">"cfi.scaled"</span>, <span class="st">"tli.scaled"</span>, <span class="st">"rmsea.scaled"</span>, <span class="st">"srmr"</span>)</span>
<span id="cb11-491"><a href="#cb11-491" aria-hidden="true" tabindex="-1"></a>), <span class="dv">3</span>)</span>
<span id="cb11-492"><a href="#cb11-492" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb11-493"><a href="#cb11-493" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-496"><a href="#cb11-496" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb11-497"><a href="#cb11-497" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb11-498"><a href="#cb11-498" aria-hidden="true" tabindex="-1"></a><span class="co"># Standardisierte Faktorladungen (nur Messmodell =~)</span></span>
<span id="cb11-499"><a href="#cb11-499" aria-hidden="true" tabindex="-1"></a><span class="fu">subset</span>(lavaan<span class="sc">::</span><span class="fu">standardizedSolution</span>(Fit), op <span class="sc">==</span> <span class="st">"=~"</span>,</span>
<span id="cb11-500"><a href="#cb11-500" aria-hidden="true" tabindex="-1"></a>       <span class="at">select =</span> <span class="fu">c</span>(<span class="st">"lhs"</span>, <span class="st">"rhs"</span>, <span class="st">"est.std"</span>, <span class="st">"pvalue"</span>))</span>
<span id="cb11-501"><a href="#cb11-501" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb11-502"><a href="#cb11-502" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-503"><a href="#cb11-503" aria-hidden="true" tabindex="-1"></a>::: {.callout-note}</span>
<span id="cb11-504"><a href="#cb11-504" aria-hidden="true" tabindex="-1"></a><span class="fu">## Stichproben- und Identifikationsvorbehalt</span></span>
<span id="cb11-505"><a href="#cb11-505" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-506"><a href="#cb11-506" aria-hidden="true" tabindex="-1"></a>Das Sechs-Faktoren-Modell hat Faktoren mit je nur **zwei Indikatoren**; solche</span>
<span id="cb11-507"><a href="#cb11-507" aria-hidden="true" tabindex="-1"></a>Faktoren sind einzeln nicht identifiziert und nur über die Faktorkovarianzen</span>
<span id="cb11-508"><a href="#cb11-508" aria-hidden="true" tabindex="-1"></a>schätzbar. In Kombination mit $N = 60$ und 12 dichotomen Items ist die CFA</span>
<span id="cb11-509"><a href="#cb11-509" aria-hidden="true" tabindex="-1"></a>**schwach gepowert**: Schätzungen können Warnungen erzeugen, und die Fit-Indizes</span>
<span id="cb11-510"><a href="#cb11-510" aria-hidden="true" tabindex="-1"></a>(CFI $&gt; .95$, RMSEA $&lt; .06$ als Zielwerte) sind mit Vorsicht zu interpretieren.</span>
<span id="cb11-511"><a href="#cb11-511" aria-hidden="true" tabindex="-1"></a>Sie werden daher gemeinsam mit den Reliabilitäts- und Rasch-Ergebnissen</span>
<span id="cb11-512"><a href="#cb11-512" aria-hidden="true" tabindex="-1"></a>bewertet.</span>
<span id="cb11-513"><a href="#cb11-513" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb11-514"><a href="#cb11-514" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-515"><a href="#cb11-515" aria-hidden="true" tabindex="-1"></a><span class="fu">## Rasch-Modell (IRT)</span></span>
<span id="cb11-516"><a href="#cb11-516" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-517"><a href="#cb11-517" aria-hidden="true" tabindex="-1"></a>Da die Langform rasch-skaliert ist, wird geprüft, ob die 12 Items das</span>
<span id="cb11-518"><a href="#cb11-518" aria-hidden="true" tabindex="-1"></a>**dichotome Rasch-Modell** erfüllen →<span class="co">[</span><span class="ot">@rasch1960</span><span class="co">]</span>. Geschätzt wird mit dem Paket <span class="in">`eRm`</span></span>
<span id="cb11-519"><a href="#cb11-519" aria-hidden="true" tabindex="-1"></a>(konditionale Maximum-Likelihood).</span>
<span id="cb11-520"><a href="#cb11-520" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-523"><a href="#cb11-523" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb11-524"><a href="#cb11-524" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: true</span></span>
<span id="cb11-525"><a href="#cb11-525" aria-hidden="true" tabindex="-1"></a><span class="co">#| eval: true</span></span>
<span id="cb11-526"><a href="#cb11-526" aria-hidden="true" tabindex="-1"></a><span class="co">#| results: "hide"</span></span>
<span id="cb11-527"><a href="#cb11-527" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb11-528"><a href="#cb11-528" aria-hidden="true" tabindex="-1"></a><span class="do">#### Rasch model ####</span></span>
<span id="cb11-529"><a href="#cb11-529" aria-hidden="true" tabindex="-1"></a><span class="co"># Rasch-Modell schätzen</span></span>
<span id="cb11-530"><a href="#cb11-530" aria-hidden="true" tabindex="-1"></a>Rasch <span class="ot">&lt;-</span> <span class="fu">RM</span>(Data_S)</span>
<span id="cb11-531"><a href="#cb11-531" aria-hidden="true" tabindex="-1"></a><span class="fu">RM</span>(Data_S)                               </span>
<span id="cb11-532"><a href="#cb11-532" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-533"><a href="#cb11-533" aria-hidden="true" tabindex="-1"></a><span class="co"># Itemparameter (Lokationen)</span></span>
<span id="cb11-534"><a href="#cb11-534" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-535"><a href="#cb11-535" aria-hidden="true" tabindex="-1"></a><span class="do">#### Person parameters ####</span></span>
<span id="cb11-536"><a href="#cb11-536" aria-hidden="true" tabindex="-1"></a>Person <span class="ot">&lt;-</span> <span class="fu">person.parameter</span>(Rasch)</span>
<span id="cb11-537"><a href="#cb11-537" aria-hidden="true" tabindex="-1"></a>Person                                 </span>
<span id="cb11-538"><a href="#cb11-538" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-539"><a href="#cb11-539" aria-hidden="true" tabindex="-1"></a><span class="co"># Personenparameter (theta)</span></span>
<span id="cb11-540"><a href="#cb11-540" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-541"><a href="#cb11-541" aria-hidden="true" tabindex="-1"></a><span class="do">#### Separation reliability ####</span></span>
<span id="cb11-542"><a href="#cb11-542" aria-hidden="true" tabindex="-1"></a><span class="fu">SepRel</span>(Person)</span>
<span id="cb11-543"><a href="#cb11-543" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb11-544"><a href="#cb11-544" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-547"><a href="#cb11-547" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb11-548"><a href="#cb11-548" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: rasch-parameter</span></span>
<span id="cb11-549"><a href="#cb11-549" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb11-550"><a href="#cb11-550" aria-hidden="true" tabindex="-1"></a>eta_raw <span class="ot">&lt;-</span> Rasch<span class="sc">$</span>etapar</span>
<span id="cb11-551"><a href="#cb11-551" aria-hidden="true" tabindex="-1"></a>betas   <span class="ot">&lt;-</span> <span class="fu">c</span>(eta_raw, <span class="sc">-</span><span class="fu">sum</span>(eta_raw))</span>
<span id="cb11-552"><a href="#cb11-552" aria-hidden="true" tabindex="-1"></a>sep     <span class="ot">&lt;-</span> <span class="fu">SepRel</span>(Person)</span>
<span id="cb11-553"><a href="#cb11-553" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-554"><a href="#cb11-554" aria-hidden="true" tabindex="-1"></a>tibble<span class="sc">::</span><span class="fu">tibble</span>(</span>
<span id="cb11-555"><a href="#cb11-555" aria-hidden="true" tabindex="-1"></a>  <span class="at">Kennwert =</span> <span class="fu">c</span>(<span class="st">"N (effektiv, ohne Extremscores)"</span>,</span>
<span id="cb11-556"><a href="#cb11-556" aria-hidden="true" tabindex="-1"></a>               <span class="st">"Anzahl Items"</span>,</span>
<span id="cb11-557"><a href="#cb11-557" aria-hidden="true" tabindex="-1"></a>               <span class="st">"Itemschwierigkeit Beta min"</span>,</span>
<span id="cb11-558"><a href="#cb11-558" aria-hidden="true" tabindex="-1"></a>               <span class="st">"Itemschwierigkeit Beta max"</span>,</span>
<span id="cb11-559"><a href="#cb11-559" aria-hidden="true" tabindex="-1"></a>               <span class="st">"Separationsreliabilität"</span>),</span>
<span id="cb11-560"><a href="#cb11-560" aria-hidden="true" tabindex="-1"></a>  <span class="at">Wert =</span> <span class="fu">c</span>(<span class="fu">nrow</span>(Rasch<span class="sc">$</span>X),</span>
<span id="cb11-561"><a href="#cb11-561" aria-hidden="true" tabindex="-1"></a>           <span class="fu">ncol</span>(Rasch<span class="sc">$</span>X),</span>
<span id="cb11-562"><a href="#cb11-562" aria-hidden="true" tabindex="-1"></a>           <span class="fu">round</span>(<span class="fu">min</span>(betas), <span class="dv">2</span>),</span>
<span id="cb11-563"><a href="#cb11-563" aria-hidden="true" tabindex="-1"></a>           <span class="fu">round</span>(<span class="fu">max</span>(betas), <span class="dv">2</span>),</span>
<span id="cb11-564"><a href="#cb11-564" aria-hidden="true" tabindex="-1"></a>           <span class="fu">round</span>(sep<span class="sc">$</span>sep.rel, <span class="dv">2</span>))</span>
<span id="cb11-565"><a href="#cb11-565" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb11-566"><a href="#cb11-566" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb11-567"><a href="#cb11-567" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-568"><a href="#cb11-568" aria-hidden="true" tabindex="-1"></a>::: {.callout-note}</span>
<span id="cb11-569"><a href="#cb11-569" aria-hidden="true" tabindex="-1"></a><span class="fu">## Befund und Stichprobe</span></span>
<span id="cb11-570"><a href="#cb11-570" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-571"><a href="#cb11-571" aria-hidden="true" tabindex="-1"></a>Die Separationsreliabilität beträgt nur $.42$: Das Modell trennt die Personen</span>
<span id="cb11-572"><a href="#cb11-572" aria-hidden="true" tabindex="-1"></a>also schwach, was das Bild der niedrigen internen Konsistenz bestätigt. Die</span>
<span id="cb11-573"><a href="#cb11-573" aria-hidden="true" tabindex="-1"></a>Itemschwierigkeiten streuen zwar breit (von $\beta = -1.98$ bis $\beta = 3.20$),</span>
<span id="cb11-574"><a href="#cb11-574" aria-hidden="true" tabindex="-1"></a>die geringe Separation bleibt davon jedoch unberührt. Generell sind bei $N = 60$</span>
<span id="cb11-575"><a href="#cb11-575" aria-hidden="true" tabindex="-1"></a>und 12 Items die CML-Schätzungen mit breiten Konfidenzintervallen behaftet.</span>
<span id="cb11-576"><a href="#cb11-576" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb11-577"><a href="#cb11-577" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-578"><a href="#cb11-578" aria-hidden="true" tabindex="-1"></a><span class="fu"># Diskussion</span></span>
<span id="cb11-579"><a href="#cb11-579" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-580"><a href="#cb11-580" aria-hidden="true" tabindex="-1"></a><span class="fu">## Ist die GEB-12 eine gute Kurzform?</span></span>
<span id="cb11-581"><a href="#cb11-581" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-582"><a href="#cb11-582" aria-hidden="true" tabindex="-1"></a>Die Bewertung folgt den Zielkriterien aus dem Analyseplan. Im Ergebnis</span>
<span id="cb11-583"><a href="#cb11-583" aria-hidden="true" tabindex="-1"></a>**verfehlt die GEB-12 die psychometrischen Zielkriterien deutlich**, während die</span>
<span id="cb11-584"><a href="#cb11-584" aria-hidden="true" tabindex="-1"></a>Langform GEB-50 ihre Gütekriterien klar erfüllt. Die einzelnen Befunde:</span>
<span id="cb11-585"><a href="#cb11-585" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-586"><a href="#cb11-586" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Interne Konsistenz:** Die Langform erreicht ein Cronbachs $\alpha = .87$</span>
<span id="cb11-587"><a href="#cb11-587" aria-hidden="true" tabindex="-1"></a>  (Split-Half $.88$, Omega total $.92$) und misst die Umwelteinstellung intern</span>
<span id="cb11-588"><a href="#cb11-588" aria-hidden="true" tabindex="-1"></a>  konsistent. Die Kurzform bleibt mit $\alpha = .50$ und einer durchschnittlichen</span>
<span id="cb11-589"><a href="#cb11-589" aria-hidden="true" tabindex="-1"></a>  Split-Half-Reliabilität von $.47$ klar unter dem Zielwert $.70$. Der zunächst</span>
<span id="cb11-590"><a href="#cb11-590" aria-hidden="true" tabindex="-1"></a>  akzeptabel wirkende Wert von Omega total $= .72$ ist nicht belastbar: Bei zwölf</span>
<span id="cb11-591"><a href="#cb11-591" aria-hidden="true" tabindex="-1"></a>  Items auf sechs Faktoren ist das Omega-Modell überparametrisiert (Omega</span>
<span id="cb11-592"><a href="#cb11-592" aria-hidden="true" tabindex="-1"></a>  hierarchical nur $.34$), sodass dieser Wert die tatsächliche Reliabilität</span>
<span id="cb11-593"><a href="#cb11-593" aria-hidden="true" tabindex="-1"></a>  überschätzt.</span>
<span id="cb11-594"><a href="#cb11-594" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Korrelation Kurz-/Langform:** Die Summenscores korrelieren nur zu</span>
<span id="cb11-595"><a href="#cb11-595" aria-hidden="true" tabindex="-1"></a>  $\rho = .30$ (Spearman) - ein lediglich mittlerer Zusammenhang. Für eine valide</span>
<span id="cb11-596"><a href="#cb11-596" aria-hidden="true" tabindex="-1"></a>  Kurzform wäre ein deutlich höherer Wert zu erwarten <span class="co">[</span><span class="ot">@smith2000sins</span><span class="co">]</span>. Die</span>
<span id="cb11-597"><a href="#cb11-597" aria-hidden="true" tabindex="-1"></a>  GEB-12 reproduziert die Personenordnung der Langform also nur eingeschränkt.</span>
<span id="cb11-598"><a href="#cb11-598" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Faktorstruktur:** Die scheinbar perfekten Fit-Indizes (CFI $= 1.00$,</span>
<span id="cb11-599"><a href="#cb11-599" aria-hidden="true" tabindex="-1"></a>  RMSEA $= .00$) sind vermutlich **Artefakte eines nicht stabil identifizierten Modells**:</span>
<span id="cb11-600"><a href="#cb11-600" aria-hidden="true" tabindex="-1"></a>  Bereits der erste, ungerichtete CFA-Aufruf konvergierte nicht, und die</span>
<span id="cb11-601"><a href="#cb11-601" aria-hidden="true" tabindex="-1"></a>  WLSMV-Lösung weist unzulässige Schätzwerte auf (eine standardisierte</span>
<span id="cb11-602"><a href="#cb11-602" aria-hidden="true" tabindex="-1"></a>  Faktorladung $&gt; 1$ bei KG01<span class="sc">\_</span>06 sowie negative Residualvarianzen). Der einzige hier belastbare Fit-Index ist der</span>
<span id="cb11-603"><a href="#cb11-603" aria-hidden="true" tabindex="-1"></a>  SRMR $= .13$ welcher über dem Grenzwert von $.08$ liegt. Die CFA bestätigt</span>
<span id="cb11-604"><a href="#cb11-604" aria-hidden="true" tabindex="-1"></a>  die Sechs-Faktoren-Struktur somit **nicht**.</span>
<span id="cb11-605"><a href="#cb11-605" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Rasch-Modell:** Die Separationsreliabilität beträgt $.42$; das Modell</span>
<span id="cb11-606"><a href="#cb11-606" aria-hidden="true" tabindex="-1"></a>  trennt die Personen also unzureichend. Die Itemschwierigkeiten streuen breit</span>
<span id="cb11-607"><a href="#cb11-607" aria-hidden="true" tabindex="-1"></a>  (von $\beta = -1.98$ für KG01<span class="sc">\_</span>06 bis $\beta = 3.20$ für KG01<span class="sc">\_</span>12). Dies spiegelt die</span>
<span id="cb11-608"><a href="#cb11-608" aria-hidden="true" tabindex="-1"></a>  beabsichtigte Mischung leichter und schwerer Items, jedoch bestätigt die</span>
<span id="cb11-609"><a href="#cb11-609" aria-hidden="true" tabindex="-1"></a>  geringe Separation das Bild der niedrigen internen Konsistenz.</span>
<span id="cb11-610"><a href="#cb11-610" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-611"><a href="#cb11-611" aria-hidden="true" tabindex="-1"></a>Eine Ursache zeigt sich in der Itemanalyse (siehe @tbl-deskriptiv): Die meisten</span>
<span id="cb11-612"><a href="#cb11-612" aria-hidden="true" tabindex="-1"></a>GEB-12-Items haben **Trennschärfen unter $.30$** (kritisch); nur KG01<span class="sc">\_</span>07,</span>
<span id="cb11-613"><a href="#cb11-613" aria-hidden="true" tabindex="-1"></a>KG01<span class="sc">\_</span>08 und KG01<span class="sc">\_</span>12 erreichen grenzwertige Werte um $.30$–$.36$. Zudem liegen</span>
<span id="cb11-614"><a href="#cb11-614" aria-hidden="true" tabindex="-1"></a>mehrere Items im Decken- bzw. Bodenbereich (z. B. KG01<span class="sc">\_</span>06 mit $P = .95$,</span>
<span id="cb11-615"><a href="#cb11-615" aria-hidden="true" tabindex="-1"></a>KG01<span class="sc">\_</span>12 mit $P = .15$). Niedrige Trennschärfen senken unmittelbar die</span>
<span id="cb11-616"><a href="#cb11-616" aria-hidden="true" tabindex="-1"></a>Reliabilität. Dies erklärt das niedrige $\alpha$ und die schwache Rasch-Trennung.</span>
<span id="cb11-617"><a href="#cb11-617" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-618"><a href="#cb11-618" aria-hidden="true" tabindex="-1"></a>In ihrer jetzigen Form ist die GEB-12 **keine</span>
<span id="cb11-619"><a href="#cb11-619" aria-hidden="true" tabindex="-1"></a>ausreichend reliable und valide Kurzform** der GEB-50. Dieser Befund ist jedoch</span>
<span id="cb11-620"><a href="#cb11-620" aria-hidden="true" tabindex="-1"></a>gut erklärbar und methodisch lehrreich: Die hohe Güte der Langform ($\alpha = .87$)</span>
<span id="cb11-621"><a href="#cb11-621" aria-hidden="true" tabindex="-1"></a>zeigt, dass das Ausgangsinstrument solide ist. Das Problem liegt also nicht im generellen</span>
<span id="cb11-622"><a href="#cb11-622" aria-hidden="true" tabindex="-1"></a>Konstrukt, sondern in der **Kürzung**. Eine bewusst über sechs heterogene</span>
<span id="cb11-623"><a href="#cb11-623" aria-hidden="true" tabindex="-1"></a>Handlungsbereiche gestreute Auswahl von nur zwei Items pro Bereich maximiert zwar die</span>
<span id="cb11-624"><a href="#cb11-624" aria-hidden="true" tabindex="-1"></a>inhaltliche Breite, minimiert aber zwangsläufig die Inter-Item-Korrelationen</span>
<span id="cb11-625"><a href="#cb11-625" aria-hidden="true" tabindex="-1"></a>(durchschnittlich nur $.07$) sowie die interne Konsistenz. Genau dies ist</span>
<span id="cb11-626"><a href="#cb11-626" aria-hidden="true" tabindex="-1"></a>eine der von @smith2000sins beschriebenen Spannungen der Kurzformentwicklung:</span>
<span id="cb11-627"><a href="#cb11-627" aria-hidden="true" tabindex="-1"></a>Breite und interne Konsistenz lassen sich bei extremer Kürzung nicht gleichzeitig</span>
<span id="cb11-628"><a href="#cb11-628" aria-hidden="true" tabindex="-1"></a>maximieren.</span>
<span id="cb11-629"><a href="#cb11-629" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-630"><a href="#cb11-630" aria-hidden="true" tabindex="-1"></a>Für eine Weiterentwicklung ergeben sich hier konkrete Ansatzpunkte: Items mit</span>
<span id="cb11-631"><a href="#cb11-631" aria-hidden="true" tabindex="-1"></a>sehr niedriger Trennschärfe oder extremer Schwierigkeit (etwa KG01<span class="sc">\_</span>06 und</span>
<span id="cb11-632"><a href="#cb11-632" aria-hidden="true" tabindex="-1"></a>KG01<span class="sc">\_</span>09) könnten gegen trennschärfere Items desselben Bereichs ausgetauscht,</span>
<span id="cb11-633"><a href="#cb11-633" aria-hidden="true" tabindex="-1"></a>die Itemzahl pro Bereich moderat erhöht oder es könnte auf eine einzelne Reliabilitätskennzahl als Hauptkriterium</span>
<span id="cb11-634"><a href="#cb11-634" aria-hidden="true" tabindex="-1"></a>verzichtet werden, zugunsten einer explizit mehrdimensionalen Konzeption. Eine</span>
<span id="cb11-635"><a href="#cb11-635" aria-hidden="true" tabindex="-1"></a>größere und heterogenere Stichprobe würde zudem stabilere CFA- und</span>
<span id="cb11-636"><a href="#cb11-636" aria-hidden="true" tabindex="-1"></a>Rasch-Schätzungen ermöglichen.</span>
<span id="cb11-637"><a href="#cb11-637" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-638"><a href="#cb11-638" aria-hidden="true" tabindex="-1"></a><span class="fu">## Einschränkungen</span></span>
<span id="cb11-639"><a href="#cb11-639" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-640"><a href="#cb11-640" aria-hidden="true" tabindex="-1"></a>Die wichtigste Einschränkung ist der **Stichprobenumfang** ($N = 60$). Er</span>
<span id="cb11-641"><a href="#cb11-641" aria-hidden="true" tabindex="-1"></a>erlaubt orientierende KTT-Kennwerte, ist für CFA und IRT mit 12 dichotomen Items</span>
<span id="cb11-642"><a href="#cb11-642" aria-hidden="true" tabindex="-1"></a>aber klein. Die Fit- und Itemparameter sind entsprechend unsicher. Aus</span>
<span id="cb11-643"><a href="#cb11-643" aria-hidden="true" tabindex="-1"></a>demselben Grund konnte der vorgeschaltete Pretest mit $N = 6$ nur die</span>
<span id="cb11-644"><a href="#cb11-644" aria-hidden="true" tabindex="-1"></a>Verständlichkeit und Durchführbarkeit absichern und keine belastbare</span>
<span id="cb11-645"><a href="#cb11-645" aria-hidden="true" tabindex="-1"></a>Itemselektion leisten (siehe @sec-pretest).</span>
<span id="cb11-646"><a href="#cb11-646" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-647"><a href="#cb11-647" aria-hidden="true" tabindex="-1"></a>Eine weitere Einschränkung betrifft den **Umgang mit fehlenden Werten**: Zur</span>
<span id="cb11-648"><a href="#cb11-648" aria-hidden="true" tabindex="-1"></a>Vereinfachung der Auswertung wurde die explizite *Keine-Angabe*-Option (NA) nicht</span>
<span id="cb11-649"><a href="#cb11-649" aria-hidden="true" tabindex="-1"></a>gesondert modelliert, sondern im Recoding mit „trifft nicht zu" (0)</span>
<span id="cb11-650"><a href="#cb11-650" aria-hidden="true" tabindex="-1"></a>zusammengefasst. Dies kann die Antwortverteilung verzerren, da eine bewusste</span>
<span id="cb11-651"><a href="#cb11-651" aria-hidden="true" tabindex="-1"></a>Enthaltung nicht dasselbe ist wie eine Verneinung des Verhaltens. Diese</span>
<span id="cb11-652"><a href="#cb11-652" aria-hidden="true" tabindex="-1"></a>Vereinfachung wurde im Vorfeld nicht ausreichend bedacht und sollte in einer</span>
<span id="cb11-653"><a href="#cb11-653" aria-hidden="true" tabindex="-1"></a>Folgeerhebung sauber getrennt behandelt werden.</span>
<span id="cb11-654"><a href="#cb11-654" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-655"><a href="#cb11-655" aria-hidden="true" tabindex="-1"></a>Schließlich handelt es sich um eine **Gelegenheitsstichprobe**, die sich</span>
<span id="cb11-656"><a href="#cb11-656" aria-hidden="true" tabindex="-1"></a>überwiegend aus Studierenden sowie Personen aus dem privaten Umfeld der</span>
<span id="cb11-657"><a href="#cb11-657" aria-hidden="true" tabindex="-1"></a>Autor:innen zusammensetzt. Sie ist damit nicht repräsentativ für die</span>
<span id="cb11-658"><a href="#cb11-658" aria-hidden="true" tabindex="-1"></a>Allgemeinbevölkerung; die Ergebnisse sind als **Machbarkeitsnachweis** der</span>
<span id="cb11-659"><a href="#cb11-659" aria-hidden="true" tabindex="-1"></a>theoriegeleiteten Kurzform zu verstehen, nicht als abschließende Validierung.</span>
<span id="cb11-660"><a href="#cb11-660" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-661"><a href="#cb11-661" aria-hidden="true" tabindex="-1"></a><span class="fu"># Literatur</span></span>
<span id="cb11-662"><a href="#cb11-662" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-663"><a href="#cb11-663" aria-hidden="true" tabindex="-1"></a>::: {#refs}</span>
<span id="cb11-664"><a href="#cb11-664" aria-hidden="true" tabindex="-1"></a>:::</span>
</code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->




</body></html>